### ISSUE TITLE
'sections' (from Cryogen docs) not available in Cryogen?

### ISSUE THREAD

**Issue by Frozenlock** [cryogen-project/cryogen#100]
I'm playing around in Cryogen and trying to come up with "sections", just like [Cryogen's documentation](http://cryogenweb.org/docs/home.html).

I've been using this part of the template:

```html
<div id="topics">
  {% for section in sections %}
  <h4>{{section.section}}</h4>
  <ul>
    {% for page in section.pages %}
    <li><a href="{{page.uri}}">{{page.title}}</a></li>
    {% endfor %}
  </ul>
  {% endfor %}
</div>
```

However, it appears that `sections` is empty.

I think Cryogen's documentation website is manually adding `sections` with a custom compiler:
https://github.com/cryogen-project/cryogen-docs/blob/master/src/cryogen/compiler.clj#L58

Is this the case? Is there a way to use `sections` in a vanilla Cryogen project?

**Comment by lacarmen** [comment]
The sections code is something that I added to the computer for the documentation site. If you want to add it to your own project then you can do something similar to what I did or you can clone cryogen-core, edit the code and then install it locally using `lein install`

**Comment by Frozenlock** [comment]
Ok, so the only way to get it is with a custom `Cryogen`.

Thanks for the answer.
