### ISSUE TITLE
Can I create a new layout?

### ISSUE THREAD

**Issue by strika** [cryogen-project/cryogen#110]
I have trouble creating a new layout. I tried to make the `html` file for the new layout and to use it in a page with `:layout` option. Existing layouts work fine, but not the new layout. Is creating new layouts possible?

**Comment by lacarmen** [comment]
Yes, you should be able to. If you give me some more details about what you're doing then I can try to help you.

**Comment by strika** [comment]
Thanks!

I'm trying to make a page called `/log`. On the page, I want to show all posts with title and full body. I tried to do this by creating a new layout `log.html` that shows all posts and then creating a new empty page `log.md` that's using the new layout. Is there a better way to do this?

**Comment by lacarmen** [comment]
Right so you would want to make the `log.html` layout and something like this at the top of your `log.md` file 

```
{:title      "This is my log"
 :layout     :log
 :page-index 0
 :navbar?    false}
```

But you would have to edit `log.md` every time you write a post, thus duplicating content, and that's not really an ideal workflow so try using [previews](http://cryogenweb.org/docs/customizing-the-index.html) instead.

**Comment by strika** [comment]
I see. Perhaps the problem was that I wasn't updating `log.md`.

Can I use previews on pages other than index?

**Comment by lacarmen** [comment]
Not at the moment, but you could clone `cryogen-core` and customize the compiler to output the previews somewhere else then install it locally as a snapshot and update the dependency in your `project.clj` to use the snapshot.

**Comment by strika** [comment]
I see. Thanks.

For now, I used the archives page instead of log. This is not ideal, because of the URL. So I'll probably try to find another solution. Thanks for help.
