### ISSUE TITLE
Integration with CI server?

### ISSUE THREAD

**Issue by yatesco** [cryogen-project/cryogen#125]
This might be a numpty question, but how do I run `lein ring-magic-to-build` which terminates after building `resources/public`?

My use case is this:
 - source project is on GitHub
 - add new .md and after checking locally I commit the .md to GitHub 
 - circleci pulls the .md and runs `lein ring-magic-to-build`
 - circleci then rsyncs to the web server

Everything works at the moment _except_ the actual building. ATM I am building locally and then committing `resources/public` as well, which is a bit blurgh.

Thanks!

**Comment by lacarmen** [comment]
I believe you're looking for [`lein run`](https://github.com/cryogen-project/cryogen#running-the-server)?

**Comment by yatesco** [comment]
Yep - apologies - right there on the front page :-).
