### ISSUE TITLE
No syntax highligting for specfic blocks?

### ISSUE THREAD

**Issue by trans** [cryogen-project/cryogen#128]
How do I prevent the syntax highlighter from predicting the language of a pre code block? I want a pre code block but without the highlighting for specific blocks. I still want highlighting for other blocks though.

**Comment by trans** [comment]
I found the solution. Use `nohighlight` as the language class.

However it didn't work at first b/c highlight.js needs to be updated to the latest version. SO there's a TODO for you :wiki:

**Comment by lacarmen** [comment]
You beat me to it :) 

Thanks for the heads up, I'll update the version now.
