### ISSUE TITLE
Feature request: klipse integration

### ISSUE THREAD

**Issue by madstap** [cryogen-project/cryogen#130]
It would be nice to have some automatic integration with [klipse](https://github.com/viebel/klipse).

Something like:
```
{:title "foo"
 :layout :post
 :klipse true}

```

I'll gladly take a shot at adding this if it's not too complex.

**Comment by lacarmen** [comment]
That would be great!

**Comment by madstap** [comment]
I made some PRs implementing this:

cryogen-project/cryogen-docs#16
cryogen-project/cryogen-core#86
cryogen-project/cryogen#138

The docs are probably a bit lacking, I would appreciate some feedback on any confusing/incomplete parts.

**Comment by lacarmen** [comment]
Thanks @madstap! I'll take a look through the PRs soon :)

**Comment by lacarmen** [comment]
I just deployed `[cryogen-core "0.1.52"]` and `[cryogen/lein-template "0.2.54"]` with the Klipse  updates. Thanks for all your work! 🎉
