### ISSUE TITLE
sass compilation

### ISSUE THREAD

**Issue by benswift** [cryogen-project/cryogen#131]
In the **Features** heading of the default "doc" post (created by `lein new cryogen`) there's a bullet point "Sass/SCSS compilation", and there's the `:sass-src` key in `config.edn`. But I can't find any other references to sass in the docs/source. Is that still a thing? I have some scss files I want to put in `themes/<mytheme>/css` - can I get cryogen to compile them automatically?

**Comment by lacarmen** [comment]
Yes, Cryogen should compile them automatically if you include the sass files in the specified `:sass-src` folder (default is `css`). From the [Cryogen site](http://cryogenweb.org/docs/configuration.html): 

|Key | Description| 
|---|---|
|sass-src|	Directory containing sass(scss) files to be compiled; nil defaults to "css". Be sure to include this directory in your resources section.|
|sass-dest|	Directory where the compiled sass would be spit out; nil defaults to "css". Be sure to include this directory in your resources section.|

And if you're interested in looking at the source, the compiler does the sass compilation [here](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L497).

**Comment by benswift** [comment]
Thanks for the quick reply. I'm just running into trouble with compass - in particular that `compass-installed?` throws an uncaught `java.io.IOException` if compass isn't installed and on the path - I guess this isn't really the desired behaviour?

Anyway, I can install compass and keep muddling on. Thanks for the help.

**Comment by lacarmen** [comment]
Yeah it sounds like it should stop the sass compilation with an appropriate error. Unfortunately I don't use sass myself so I'm not aware if there's a better alternative to compiling sass automatically. If you've got an insight I'd love to hear it.

**Comment by benswift** [comment]
So I do have the `sass` cli too installed, I just didn't have `compass` as well. And the `sass` command would have worked just fine without the `--compass` option I think. So perhaps the best/easiest option is to at least catch the exception in the shell command in `compass-installed?`.

Once I've got it all up and running you can use my blog as another example. But I'm not really an expert at this web stuff :)

**Comment by lacarmen** [comment]
Fixed by cryogen-project/cryogen-core#75
