### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by HomoEfficio** [cryogen-project/cryogen#133]
when executing 'lein ring server' in Git Bash Shell(MINGW64) on Windows 7, following error ocurrs:

![](http://i.imgur.com/tzfqWze.png) 

![](http://i.imgur.com/KpILMYA.png)

I guess that cryogen is using fullpath of a .md file in Git Bash Shell(MINGW64) on Windows.

I tried the same thing in Mac, everything worked good.

**Comment by lacarmen** [comment]
Sounds like this is the same issue as cryogen-project/cryogen-core#74. Someone's provided a fix, so I'll have that reviewed and pushed soon. :)

**Comment by lacarmen** [comment]
Please try again with `cryogen-core 0.1.44` @HomoEfficio

**Comment by HomoEfficio** [comment]
Thank you for the quick reply.
The Date parsing problem looks patched.

But this time I met NullPointerException, with lein-template-0.2.50 and cryogen-core-0.1.45.

![20161219_cryogen-err1](https://cloud.githubusercontent.com/assets/17228983/21297690/7a9ea6ca-c5c7-11e6-8907-3200362d0350.png)

![20161219_cryogen-err](https://cloud.githubusercontent.com/assets/17228983/21297686/6d90a384-c5c7-11e6-8d1a-f4301b1b6ae3.png)

**Comment by lacarmen** [comment]
@HomoEfficio my apologies, there was a bug with a new feature that was added. If you change the `cryogen-core` dependency in the `project.clj` of your generated cryogen template to `0.1.46` then it should compile.

**Comment by HomoEfficio** [comment]
@lacarmen  

Thank you so much.

Finally it works perfect!!

![20161220_clojureok](https://cloud.githubusercontent.com/assets/17228983/21319602/396903be-c651-11e6-8066-1a86cfabb586.png)

**Comment by lacarmen** [comment]
@HomoEfficio I'm glad to hear that!
