### ISSUE TITLE
Markdown Parser

### ISSUE THREAD

**Issue by rjb25** [cryogen-project/cryogen#134]
This is what I have in my post's markdown
[Cryogens site](https://github.com/cryogen-project/cryogen "Cryogen Github")

`[Cryogens site](https://github.com/cryogen-project/cryogen "Cryogen Github")`
 it will go to 
https://github.com/cryogen-project/cryogen%20%22Cryogen%20Github%22
instead of 
https://github.com/cryogen-project/cryogen    
with the the hover over name being "Cryogen Github"
Obviously from within github markdown it works. However I think the interpreter is failing.
My info:
Leiningen 2.6.1 on Java 1.8.0_101 Java HotSpot(TM) 64-Bit Server VM
Also I have downloaded Cryogen very recently.
Ubuntu 14.04.4 LTS

**Comment by v6** [comment]
// , I've run into this as well. What version of Cryogen are you working with? 

Can you post some stats about your host system, too?

**Comment by lacarmen** [comment]
@rjb25 Cryogen uses [markdown-clj](https://github.com/yogthos/markdown-clj). It does not currently support that title syntax. (As seen in the [live demo](https://rawgit.com/yogthos/markdown-clj/master/demo/markdown.html))

This would be an issue to open under the markdown-clj repo.

**Comment by lacarmen** [comment]
I've opened an issue about adding support for this syntax in the markdown-clj project.
