### ISSUE TITLE
404.html which uses base theme

### ISSUE THREAD

**Issue by benswift** [cryogen-project/cryogen#136]
I'm hosting on GH pages, which lets you provide a top-level `404.html` to serve up as a custom 404 page.

I'd like to have use the same "skeleton" html from my theme's `base.html` with a custom body (either in html or md, I don't mind) which then gets placed in a top-level `404.html` upon compilation. What's the easiest way to achieve this?

**Comment by lacarmen** [comment]
The 404 page is copied to the `public` folder as a resource right now so unfortunately, there isn't currently a way to inject some 404 content into the base html.

 If you'd like to see this functionality added feel free to open a separate issue or submit a PR :)

**Comment by benswift** [comment]
Ok, sure, I'll have a look at putting something together.
