### ISSUE TITLE
Wrong previous page url when it has :home? set to true

### ISSUE THREAD

**Issue by armed** [cryogen-project/cryogen#137]
Hi, 

Steps to reproduce:
1. Create new site `lein new cryogen my-site`
2. Set `:home? true` in pages/about.md
3. Open site and use link "Another page >>" to open second page
4. Try to navigate back using "<< About" - error comes here (wrong ur)

It seems that `:home? true` page is not in `pages-output/about` directory anymore, it is `/index.html`.

**Comment by lacarmen** [comment]
Yes, adding the `:home? true` flag to a page will cause it to be used as the site's landing page. Perhaps previous/next links should not be included if the prev/next pages have been flagged with `:home?`?

**Comment by armed** [comment]
In my case I wanted previous link's href to be "/". I modified `page.html` in theme:
```
    <div id="prev-next">
        {% if page.prev %}
          {% ifequal page.prev.uri "/pages-output/<page name with :home? true>/" %}
          <a id="prev" href="/">&laquo; {{page.prev.title}}</a>
          {% else %}
          <a id="prev" href="{{page.prev.uri}}">&laquo; {{page.prev.title}}</a>
          {% endifequal %}
        {% endif %}
        {% if page.next %}
        <a id="next" href="{{page.next.uri}}">{{page.next.title}} &raquo;</a>
        {% endif %}
    </div>
```
Currentpy `page.prev` and `page.next` params has only `title` and `uri` fields. It would be cool to have all fields from page header in this variables.

**Comment by lacarmen** [comment]
> In my case I wanted previous link's href to be "/". 

I'm not sure if this would be the most intuitive solution. It looks like there are 3 possibilities:

1. Don't use prev/next links to point at `:home?` pages
2. If the page is a `:home?` page then have the link(s) point to `"/"`
3. Compile `:home?` pages as the index but also compile them as a "regular" page so they still show up in the `pages-output` directory. That way the current prev/next linking scheme still works.

I think option 3 would fit the general use case the best and a workaround like the one you've done can be used to allow for the first two options. In any case, including all the page metadata in the `page.prev` and `page.next` params would indeed be useful.

**Comment by armed** [comment]
> I'm not sure if this would be the most intuitive solution. 

You are right, 1-st solution is preferable. And I can add prev link to "/" when `page.prev` is `nil`. And metadata in prev/next for other cases also could help.

**Comment by lacarmen** [comment]
I just pushed out version `0.1.48` of `cryogen-core` with the 1st solution implemented + the extra metadata. Let me know if this is what you're looking for. :)

**Comment by armed** [comment]
Hey, @lacarmen 

Just tried new version and noticed that `:home?` page ignores `:layout` option and uses home template. Is it intentional? My home page layout is set to `page`.

**Comment by lacarmen** [comment]
Sorry! I introduced a slight regression. It should respect the `:layout` option that you specify in the page metadata. I just pushed `0.1.49` with a fix.

**Comment by armed** [comment]
It now respects `:layout`, but does not pass `page` param to template but passes `post` param.

**Comment by lacarmen** [comment]
Oh I see why that would be annoying for you if you're using the `page` layout. It was passing both `page` and `post` before but they had the same data in them so I thought it would be okay to remove the `page` param. 

`0.1.50` :crossed_fingers:

**Comment by armed** [comment]
@lacarmen thanks! Works like a charm!
