### ISSUE TITLE
Code block sizing affected by highlight js.

### ISSUE THREAD

**Issue by rjb25** [cryogen-project/cryogen#142]
A code block with hljs class is bigger than one that is without it. I am avoiding highlighting for some of the code blocks I have and find this difference in size ugly. Is this intended behavior?

**Comment by rjb25** [comment]
Also a block marked with like:
\`\`\`text
\`\`\`
Will have this weird lack of padding.
I the fix is as simple as adding what is given by the `.hljs` class to the `pre code` class. I will send a pull request.

**Comment by lacarmen** [comment]
A new template has been deployed with the fix.
