### ISSUE TITLE
Disable auto highlight in config.edn?

### ISSUE THREAD

**Issue by rjb25** [cryogen-project/cryogen#144]
Wondering if you were interested in adding a setting that would make highlight.js only highlight when you specified like

\`\`\`clojure
(print "hello world")
\`\`\` 
And would leave
\`\`\`
(print "hello world")
\`\`\`
as plain text.
I fixed this for myself, by going into `resources/templates/themes/blue/html/base.html` and making the following change on about line 95:
```
<script>hljs.initHighlightingOnLoad();</script>
```
to
```
<script>
hljs.configure({languages: []});
hljs.initHighlightingOnLoad();
</script>
```
If you could automate this in the config or on a page by page basis I think it would improve the product by saving time constantly typing \`\`\`text anytime we want highlighting off which for me is the majority case.

**Comment by lacarmen** [comment]
I believe that would conflict with how highlight.js works:

> [highlight.js] will find and highlight code inside of \<pre\>\<code\> tags; _it tries to detect the language automatically_. If automatic detection doesn’t work for you, you can specify the language in the class attribute:

If you don't want your code highlighted then I think it makes sense to specify your bocks as \```text.

**Comment by rjb25** [comment]
Ok, it is simple enough to do manually I guess. It may be what it is meant to do, but not what I, and possibly other users want to do.
