### ISSUE TITLE
Feature request: subscribe and unsubscribe

### ISSUE THREAD

**Issue by shaulid** [cryogen-project/cryogen#146]
Hi, 

Since this is a blog generator, it'd be useful if we could have people subscribe/unsubscribe to a mailing list and get the new posts by e-mail. I know this requires it to be something beyond a "static file generator", but I guess many people who run a blog need this kind of functionality.

**Comment by lacarmen** [comment]
While it's not possible to support mailing lists without moving being a static site generator like you said, Cryogen does generate RSS feeds (one with all posts, and ones filtered by tag). 

If your readers use some sort of RSS feed reader then they could get updates this way.

**Comment by shaulid** [comment]
Simple people prefer to subscribe by e-mail and almost nobody (except for highly technical people) uses RSS feeds. I consider a solution by making a mailing list using another platform, and when I write a new post send it (or link to it) from the mailing list. 
Still pondering whether that may serve me well or I should move to a more robust blogging platform (though I love Clojure and prefer to keep using cryogen).
Anyhow, thanks for making cryogen.

**Comment by lacarmen** [comment]
Unfortunately email lists are outside of the scope of this project. I hope you can find a suitable solution. :)
