### ISSUE TITLE
Alternative breeze tutorial.

### ISSUE THREAD

**Issue by rjb25** [cryogen-project/cryogen#148]
I made a layman's tutorial for using cryogen. Maybe link to it in the tutorial as a walk through? Up to you, thought I'd let you know. I know I had a lot of trouble reading the docs when I was first trying to get a hang of cryogen. Hoping this will help other's journey be less tedious. If you find any issues, or want me to add anything to my tutorial I can easily modify it.

[My tutorial](http://codelifeblog.com/posts/12-22-2016-cryogen/)

**Comment by lacarmen** [comment]
Thanks for the feedback! If it's okay with you, maybe I'll take some pieces from your blog post and create an FAQ page for the documentation site?

**Comment by rjb25** [comment]
Wouldn't it be easier to just link to the post? If it's because the post
looks tacky im very open to criticism and may be able to fix it up. And
yeah you can use that post's content however you like.

**Comment by lacarmen** [comment]
It's not that, it would just be easier from a maintenance perspective to keep everything in the same place in case I need to update something or add more content.
