### ISSUE TITLE
custom home page from summaries / short descriptions

### ISSUE THREAD

**Issue by bagdemir** [cryogen-project/cryogen#149]
Is that possible to create a custom home page from summaries of the blog posts, like in generated static web sites by Hakyll, e.g. https://jaspervdj.be ?

**Comment by lacarmen** [comment]
You can do something similar by setting `previews?` to `true` and then editing `previews.html` accordingly to add the "about" section.

**Comment by lacarmen** [comment]
Home page options are documented [here](http://cryogenweb.org/docs/customizing-the-index.html).
