### ISSUE TITLE
Make Cryogen github.io page source available as an example

### ISSUE THREAD

**Issue by RickButler** [cryogen-project/cryogen#151]
It doesn't appear that you can open issues on cryogen-project.github.io for Cryogen or I would have put this there. 

The Cryogen github homepage looks like it has a lot of custom logic and would serve as a good example of what can be done with Cryogen, I could only find the compiled code available in master. I would suggest creating a separate dev branch with the pre-build code for use as an example.

**Comment by RickButler** [comment]
I'm an idiot foudn the docs project.

**Comment by lacarmen** [comment]
Haha I'm glad you ended up finding the source code. Maybe I should put a link to the source project on the docs site?

**Comment by RickButler** [comment]
@lacarmen, I like that idea.
