### ISSUE TITLE
Error "No reader function for tag object" on `lein ring server`

### ISSUE THREAD

**Issue by Sgoettschkes** [cryogen-project/cryogen#154]
I tried starting a new project with cryogen. I executed the following commands:

```
lein new cryogen project
cd project/
lein ring server
```

This returns the following exception:

`Exception in thread "main" java.lang.RuntimeException: No reader function for tag object, compiling:(/tmp/form-init5757147463169772256.clj:1:1495)`

I was also unable to get it running using `lein ring server-headless`. Running `lein run` works and creates the static resources in `resources/public`.

I am running Clojure 1.8.0 (OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11) with Leiningen 2.8 (Leiningen 2.8.0 on Java 1.8.0_131 OpenJDK 64-Bit Server VM).

If somebody could point me in the right direction, I'm willing to do the research and try to fix it/do a PR!

**Comment by Sgoettschkes** [comment]
I was able to figure it out. This is unrelated to cryogen but is rooted in leiningen. The related issue is https://github.com/technomancy/leiningen/issues/2328

The solution (for now) is downgrading leiningen through `lein upgrade 2.7.1`.

**Comment by lacarmen** [comment]
Glad to hear it's not an issue in Cryogen. I'll leave this open for a little while in case anyone runs into the same problem.

**Comment by Sgoettschkes** [comment]
Upgrading to Leiningen 1.8.1 fixed this issue.
