### ISSUE TITLE
klipse not working with the ASCIIDOC posts

### ISSUE THREAD

**Issue by abhi18av** [cryogen-project/cryogen#156]
Hi **Cryogen** team 

I'm in the process of moving my personal blog to `cryogen` and I was following instructions for integrating `klipse` within a post. But it doesn't seem to work with the `ASCIIDOC` version of cryogen.

```sh

{:title "Adoc Page"
 :layout :page
 :page-index 0
 :klipse true
 :navbar? true}

== Adoc Page ==

We support http://asciidoc.org/[asciidoc] too!


```klipse-cljs
(map #(* % %) (range 10))
```
```

For ASCIIDOC I've tried to use 

```sh
.klipse-cljs
[source, clojure]
----
(defn sqr [x]
   (* x x ))
   
   (println (sqr 10))
----
```

But it doesn't seem to make any difference

**Comment by lacarmen** [comment]
It appears asciidoc and markdown convert markup for code blocks differently.

    ```klipse-cljs
    (map #(* % %) (range 10))
    ```
In markdown:
```
<pre><code class="klipse-cljs">(map #(* % %) (range 10))</code></pre>
```

In asciidoc:
```
<pre class="highlight"><code class="language-klipse-cljs" data-lang="klipse-cljs">(map #(* % %) (range 10))</code></pre>
```
Note how the css classes are different.


An easy solution is to just adjust the klipse selectors accordingly:
```
{...
:hide-future-posts? true

:klipse {:settings {:selector ".language-klipse-cljs"}}

:debug? false}
```

**Comment by abhi18av** [comment]
Thanks a lot @lacarmen . This was so obvious :smile:

**Comment by lacarmen** [comment]
No worries! I'm glad it's an easy fix 😄
