### ISSUE TITLE
java.text.ParseException Unparseable date: "resources/" when naming project "githubpages"

### ISSUE THREAD

**Issue by dmichulke** [cryogen-project/cryogen#158]
For ```lein run``` and ```lein ring server``` I get

```
loading module: Markdown parser
compiling assets...
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 1938
                           clojure.core/pmap/fn/fn                 core.clj: 6736
            cryogen-core.compiler/read-posts/fn/fn             compiler.clj:  151
                  cryogen-core.compiler/parse-post             compiler.clj:  131
             cryogen-core.compiler/parse-post-date             compiler.clj:   66
                        java.text.DateFormat.parse          DateFormat.java:  366
               java.text.ParseException: Unparseable date: "resources/"
    errorOffset: 0
java.util.concurrent.ExecutionException: java.text.ParseException: Unparseable date: "resources/"
"Elapsed time: 407.620167 msecs"
```

The difference with the other (closed) issues is that this is on Linux (```4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```).

```lein version``` prints ```Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM```

and ```lein deps :tree``` has two conflicts that I can resolve with the lines

```[compojure "1.6.0" :exclusions [commons-codec]]```

and

``` :plugins [[lein-ring "0.12.2"]]```

in project.clj but both the error persists.

The rest is unchanged, i.e., immediately after ```lein new cryogen ...```

**Comment by SVMBrown** [comment]
Hi, I am unable to reproduce this behaviour. I suspect there is something strange about either your directory structure, or your config. One thing you could try as a sanity check is deleting your local leiningen cache ( `rm -r ~/.m2/repository/cryogen*` ), and rebuilding with `lein new cryogen ...`. If this doesn't work please provide your `resources/templates/config.edn`

**Comment by dmichulke** [comment]
OK, I tried your tests and I gotta say this is strange: The error only occurs if I call the project "githubpages"

So please try ```lein new cryogen githubpages``` and then ```lein ring server```. I hope you can reproduce and if so, I'd be very interested as to why this name doesn't work :-)

**Comment by lacarmen** [comment]
That's really weird, I'll try to figure out what's going on. Thanks for the additional info :)

**Comment by dmichulke** [comment]
No worries. Sounds like you could reproduce the problem then?
In any case, thank you for your work, it works flawlessly when using the correct name ;-)

**Comment by lacarmen** [comment]
Yup, I got the same error when naming the project "githubpages". Happy to hear that it's working for you otherwise :)

**Comment by ChinmoyDn** [comment]
I got the same error when tried to create with the project name ```lein new cryogen blog-pages```

**Comment by lacarmen** [comment]
I suspect it's because the project name ends with "pages" and the compiler looks for md/asc files under the dir "pages" by default.

**Comment by bombaywalla** [comment]
Is this still an issue?

I did the following
```shell
lein new cryogen blog-pages
cd blog-pages
lein run
```
and did not get any errors or exceptions.

**Comment by holyjak** [comment]
Doing

    lein new cryogen githubpages
    lein serve

works for me so the problems seems solved.
