### ISSUE TITLE
Pushing changes to Github Pages

### ISSUE THREAD

**Issue by communalismwiki** [cryogen-project/cryogen#159]
Hi everyone,
I'm new to Cryogen/static site generators in general, so please bear with me. I am hosting a site on Github Pages.
I just set up a site, and I trying to change the theme. So, I change the theme in the config file. Now, when I try to push the changes to Git, I receive a  "nothing to commit, working directory clean" message. How do I push these changes to Git?
I also am unsure how the site generator works. I'm only hosting the Public folder on Github, but how does the generator interact with it then?

Thank you,
Aaron

**Comment by lacarmen** [comment]
It's easiest to keep the actual project and your github pages site in two separate repos. 

After changing the theme in the config file you need to run `lein run` from the project root to recompile your pages (which will be outputted to your public folder.) Once you've recompiled the site you can copy the public folder to your github pages repo and push the changes.

**Comment by communalismwiki** [comment]
Ok that is the piece that I was missing. lein run will update all of the files, and then gi will be able to track them. Thank you!

**Comment by lacarmen** [comment]
You're welcome!
