### ISSUE TITLE
Github Pages CNAME error

### ISSUE THREAD

**Issue by communalismwiki** [cryogen-project/cryogen#160]
The documentation for setting up Cryogen with hosting on GithubPages does not clearly detail the steps needed if cryogen will be hosted on a root level domain (i.e. www.cryogen.com)
The error is that the docs tell user to "For the Cryogen part, create a file called CNAME at resources/templates/CNAME with contents similar to this:"
and then to add the CNAME resource to config.edn

This creates an error when hosting on Github Pages because Github tries to automatically add a CNAME file to the root of the Master branch. If there is already a CNAME file from cryogen, then Github breaks. (This method still works if the blog is hosted on a url extension, i.e. cryogen.com/blog)

Instead, the docs should state that if the site is to be hosted on a root level domain, then the CNAME resource should not be added to config.edn

**Comment by communalismwiki** [comment]
Here is a different solution also, copy the CNAME file from the CNAME folder and paste it into the resources/templates folder.

**Comment by lacarmen** [comment]
> The error is that the docs tell user to "For the Cryogen part, create a file called CNAME at resources/templates/CNAME with contents similar to this:" 

I believe this was the way to do it before Github updated the way Github Pages are configured. The documentation should be updated to reflect that. If you'd like to do a PR that would be great. :) 

> Here is a different solution also, copy the CNAME file from the CNAME folder and paste it into the resources/templates folder. 

I'm not sure I understand this solution. From what I know there is only a CNAME file, not a folder.

**Comment by communalismwiki** [comment]
Either I have confused myself greatly trying to go back and look at it now, or I did it wrong from the beginning. I'm going to close, thanks!
