### ISSUE TITLE
Include SEO

### ISSUE THREAD

**Issue by dmichulke** [cryogen-project/cryogen#164]
The site doesn't add meta tags "description" and "keywords", something quite valuable to most search engines.

**Comment by lacarmen** [comment]
The HTML templates are available to you when you make a new Cryogen project so you can add the meta tags to your template if you wish.

**Comment by dmichulke** [comment]
Thanks for your response. Sorry if that might have come across a little blunt! I use cryogen (and I'm very satisfied) that's why I find these minor things :-)

I already did the fix you mentioned but I thought it might make sense to make it part of the config, maybe even reuse the description key for the meta description. As a simple alternative, one might add a small paragraph about this somewhere on the project page.

It's low priority nevertheless.

**Comment by lacarmen** [comment]
No worries, I'm glad you're happy with cryogen! 

Everything in the config is made available to the templates through selmer, so you can use whatever keys you want if you want additional config values. Adding the description tag to the templates would be good, I think most people don't remember to add it themselves.

**Comment by lacarmen** [comment]
Closing since #195 adds the description tag. Can reopen if more SEO needs to be addd.
