### ISSUE TITLE
ES6 / ES.next compilation

### ISSUE THREAD

**Issue by devth** [cryogen-project/cryogen#165]
I imagine this working similar to sass compilation.

**Comment by holyjak** [comment]
@devth Do you sue much JS in your site? If not then perhaps it is ok to keep to ES5 and keep Cryogen simpler and faster?

**Comment by devth** [comment]
Yeah it's probably ok to keep ES5. I don't currently use a ton of JS.

What would be really cool is if it compiled CLJS.
