### ISSUE TITLE
Clean urls without trailing /

### ISSUE THREAD

**Issue by devth** [cryogen-project/cryogen#166]
Related to https://github.com/cryogen-project/cryogen/issues/89 – how about supporting even cleaner urls without the trailing slash?

**Comment by lacarmen** [comment]
👍 I won't have time to look at this but if you could do a PR that would be great!

**Comment by devth** [comment]
The only way to do this would be to generate html files instead of directories. 

e.g instead of

```
resources/public
├── archives
│   └── index.html
...
```

Cryogen should generate a file structure like:

```
resources/public
└── archives.html
```

Then we could simply link to `/archives` and we wouldn't get the 301 to `/archives/`.

Reference [this StackOverflow post](https://stackoverflow.com/questions/33270605/github-pages-trailing-slashes).

**Comment by lacarmen** [comment]
Ah, I wasn't aware of the difference when #89 was implemented. Should `:clean-urls?` still be an option then? Are there use cases for needing to explicitly link to a `.html`?

**Comment by devth** [comment]
I think it should be the default 😀 not sure if others would want the ability to turn it off.

**Comment by devth** [comment]
So I think the current `:clean-urls? false` behavior is what I want. The only change would be to build the `navbar-pages` without the `.html` extension.

I tried this out on my site with `:clean-urls? false`. Both of these work:

- https://yetibot.com/user-guide
- https://yetibot.com/user-guide.html

But all the links in the header have the `.html` extension that I don't want.

And for some reason my images don't work any more (using `lein ring server` but they work in the compiled github pages site. That's a separate issue.

**Comment by devth** [comment]
So the only change I want is to remove `.html` here: https://github.com/devth/cryogen-core/blob/67ef4b2d77939e69cefeb13119378f215fe3734c/src/cryogen_core/compiler.clj#L210

Think that should be a separate config option? Or should that be the *only* difference when `:clean-urls? true`? Basically we'd undo all the work in https://github.com/cryogen-project/cryogen-core/pull/64 and make this tiny change.

**Comment by devth** [comment]
We would also need to make a change to the local dev ring server to be able to properly serve html files without the `.html` extension.

**Comment by lacarmen** [comment]
Right, so we'd want to generate the files as we were doing before #64 and remove the `.html` from links when `:clean-urls?` is set to `true`. 

The issue with your images is strange - that shouldn't be affected by this change...

**Comment by devth** [comment]
I got the images thing fixed locally after the above change to `wrap-subdirectories`.

I'll try to get a PR in for reverting #64 and adjusting behavior.

**Comment by lacarmen** [comment]
> I got the images thing fixed locally after the above change to `wrap-subdirectories`.

Ah okay, good to hear :)

**Comment by devth** [comment]
Should be all set!

**Comment by devth** [comment]
Hey @lacarmen - have a minute to check my PRs? Thanks.

**Comment by lacarmen** [comment]
Hey @devth, I looked at them briefly when you opened them but I haven't tested everything together yet. Hopefully I can find some time to do that by next week. :)

**Comment by luchiniatwork** [comment]
Ah I see... we wanted to remove the trailing `/`. This change is fundamentally ok (if not great) with my Netlify hosting. However, when migrating to AWS, I'm finding out that S3 does not automatically append `.html` when serving files. 😞

**Comment by luchiniatwork** [comment]
Other static site generators seem to have the same challenge: https://github.com/jescalan/roots/issues/684

The solution at https://stackoverflow.com/questions/23463679/s3-static-pages-without-html-extension feels a bit wrong (and definitely hacky in an automated environment).

**Comment by devth** [comment]
@luchiniatwork do you think Cryogen should provide 3 options instead of boolean `:clean-urls?`? 

Alternatively, maybe CI/CD could handle this:

> You have to set the meta data of the file Content-type to text/html AND rename the file removing the .html of the end.

**Comment by luchiniatwork** [comment]
> You have to set the meta data of the file Content-type to text/html AND rename the file removing the .html of the end.

For now, this is what I'm doing but it just feels a bit wrong. For instance, I now have a script to rename all .html files before uploading to S3. Then I needed to change on all AWS settings where index page and error page point to traditional "index.html" and "404.html" to "index" and "404". I could selectively rename files but then I'm going deeper into the rabbit hole 😄 

It does seem like more options to `:clean-urls?` would be great. Some kind of `:url-style` with at least three different settings like `:index`, `:html` and `:no-extension-html`.

In some cases though, even the `:no-extension-html` might be problematic. I.e. the script I have to detect if the file is an html relies on a mime-detection library that uses the file extension to return `text/html`. I need to know which files are html to set the meta data accordingly.

**Comment by lacarmen** [comment]
There's always going to be outliers but if we can support the most common use cases then I'm happy. 

> Some kind of :url-style with at least three different settings like :index, :html and :no-extension-html 

Just to clarify: `:index` would be `archives/index.html`, `:html` would be `archives.html` and `:no-extension-html` would be `archives.html` but linking to `/archives`?

**Comment by luchiniatwork** [comment]
> Just to clarify: `:index` would be `archives/index.html`, `:html` would be `archives.html` and `:no-extension-html` would be `archives.html` but linking to `/archives`?

That's correct for `:index` and `:html`... for `:no-extension-html` my initial thought was to generate `archives` linking to `/archives` but I'm having second thoughts - would it be too S3 specific? Thoughts?

**Comment by lacarmen** [comment]
I don't use S3 myself, so unfortunately I can't comment on that 😞

**Comment by niamu** [comment]
### Proposed Solution for "clean URLs"

There are two layers to the problem:

1. Generated links in HTML content
2. Directory structure and file names output

To keep these matters separate and clear, I will refer to them as `:clean-urls-links?` for **1** and `:clean-urls-filename?` for **2**.

#### S3 Clean URLs Use Case

We revert to the old way of of outputting files with "/index.html" appended and we keep link generation the same as it is now with no trailing slash. This results in a harmless 302 redirect to the resource with the trailing slash which I think should be perfectly acceptable.

`:clean-urls-links? true` - results in non-trailing slash link
`:clean-urls-filename? true` - results in "/index.html" appended

#### GitHub Pages Clean URLs Use Case

Everything remains as it is now with no changes to how `:clean-urls?` functions in either link generation within HTML content. Outputs files as they work now for `:clean-urls?` as well.

`:clean-urls-links? true` - results in non-trailing slash link
`:clean-urls-filename? false` - results in just a simple ".html" file

#### Dirty URLs Use Case

How everything works currently if you have `:clean-urls?` set to false.

`:clean-urls-links? false` - results in ".html" links
`:clean-urls-filename? false` - results in just a simple ".html" file

---

I think this proposal is the happiest compromise, but I don't like that it can still result in cases where users can generate outputs that will not function in some environments:

`:clean-urls-links? false` - results in ".html" links
`:clean-urls-filename? true` - results in "/index.html" appended

This case would result in broken links on S3 at least, possibly other cases as well. This could potentially be resolved by generating errors when this specific combination of configuration is set. I think that would work best and doesn't break a use case that I can think of.

I'm not necessarily advocating split `:clean-urls?` into 2 separate configuration options. We could just as easily have only 3 acceptable values such as `[:s3-clean-urls :github-clean-urls :dirty-urls]` or whatever else we can think of for descriptive names.

**Comment by lacarmen** [comment]
@niamu Thanks for the detailed proposal! 

I'd prefer to stick to a single config option, and we should change it to `:clean-urls` or something else then. We can define the acceptable values in the [config schema](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/schemas.clj#L28).

@devth @luchiniatwork would this work for you?

**Comment by devth** [comment]
sounds good to me 👍

**Comment by luchiniatwork** [comment]
Likewise here @lacarmen ...

**Comment by lacarmen** [comment]
Great 😄 

@devth @niamu @luchiniatwork would any of you like to work on this? I'm currently wrapping up with cryogen-project/cryogen-core#117 and it would be great if I could release it all together.

**Comment by niamu** [comment]
I have time to work on it later today and can probably finish it by tomorrow at the latest I think. But if someone else has more time and wants to work on it, feel free to message back here and let me know. Otherwise assume I'll finish the work.

**Comment by luchiniatwork** [comment]
I'm going through a lot on my side for a few weeks 😢
