### ISSUE TITLE
Add note to  docs on how best to create links between pages/posts

### ISSUE THREAD

**Issue by willfurnass** [cryogen-project/cryogen#167]
Have I missed this info in the docs?  Would be useful.  

I imagine http://cryogenweb.org/docs/writing-posts.html would be the best place for this info.

**Comment by lacarmen** [comment]
Just to clarify, are you looking for information on how to add hyperlinks in pages/posts? (Or something different?)

**Comment by willfurnass** [comment]
Yep, specifically _between_ pages/posts.  I ended up using '/posts-output/2018-01-30-my-post.md` as my link target.   I know it's only a small thing and probably very obvious but thought it could be useful to add to the docs anyway.
