### ISSUE TITLE
Error Using Lotus Theme

### ISSUE THREAD

**Issue by kmarker1101** [cryogen-project/cryogen#168]
When I attempt to use the Lotus theme I get 

`java.io.IOException: error=2, No such file or directory
java.io.IOException: Cannot run program "sass": error=2, No such file or directory`

Any idea's? I am sure I am just missing something but? I am using the latest version of cryogen. All other themes work great.

**Comment by lacarmen** [comment]
The Lotus theme has sass files so you'll need sass installed on your machine.

**Comment by kmarker1101** [comment]
Thanks

**Comment by rubinglen** [comment]
i tried downloading the sass package and extracting it to usr/local/bin which didn't work.  so instead just installed ruby-sass on ubuntu, which took care of these dependencies.  sudo apt-get install ruby-sass
