### ISSUE TITLE
Not working on Gitlab pages

### ISSUE THREAD

**Issue by alanmarazzi** [cryogen-project/cryogen#169]
Hi, everyone, I really like Cryogen, but I can't make it work on Gitlab pages. 
The issue is that the content should live in `public` folder at the root of the project, which of course is not what Cryogen does. Not too bad: I simply move the `resources/public` folder into a root `public` one in the job configuration. Cool up to this point.

Now I can actually go to the homepage `domain/project-name` and the content is there, but as soon as I try to click any internal link I get 404. The issue is that the uris are pointing to `domain/uri`, while it should be `domain/project-name/uri` and I can't seem to make it work.

This is my `config.edn`:

```clojure
{:site-url             "https://username.gitlab.io/"
 :post-root            "posts"
 :page-root            "pages"
 :post-root-uri        "posts-output"
 :page-root-uri        "pages-output"
 :tag-root-uri         "tags-output"
 :author-root-uri      "authors-output"
 :blog-prefix          "blog/"
 :rss-name             "feed.xml"
 :rss-filters          ["cryogen"]
 :recent-posts         3
 :post-date-format     "yyyy-MM-dd"
 :archive-group-format "yyyy MMMM"
 :sass-src             []
 :sass-path            "sass"
 :compass-path         "compass"
 :theme                "nucleus"
 :resources            ["img"]
 :keep-files           [".git"]
 :disqus?              false
 :disqus-shortname     ""
 :ignored-files        [#"\.#.*" #".*\.swp$"]
 :previews?            false
 :posts-per-page       5
 :blocks-per-preview   2
 :clean-urls?          true
 :collapse-subdirs?    false
 :hide-future-posts?   true
 :klipse               {}
 :debug?               false}
```

**Comment by lacarmen** [comment]
Gitlab pages setup should be very similar to [Github pages setup](http://cryogenweb.org/docs/deploying-to-github-pages.html). It sounds like you need to set your `blog-prefix` to your `project-name`.

**Comment by alanmarazzi** [comment]
I already tried that, it is `blog` indeed, but the issue is that Gitlab looks for content in the `public` folder and that's going to be already shown at `username.gitlab.io/blog`, so if I don't use the prefix I will see the homepage and nothing else (uris point at the root), while if I use the prefix I don't get anything (it goes under `username.gitlab.io/blog/blog`).

Here as a reference: https://docs.gitlab.com/ee/user/project/pages/getting_started_part_two.html#urls-and-baseurls

P.S.: I tried with other SSGs (Jekyll, Pelican) and they are working, but I would really like to use Cryogen

**Comment by alanmarazzi** [comment]
You're right!!! Now I feel really bad 😞 I always have issues with paths!!!

Anyway, for further memory if someone wants to deploy to Gitlab pages this is the `config.edn` parts you have to be careful to:

```clojure
{:site-url             "https://username.gitlab.io/"
 :blog-prefix          "blog/"}
```

And this is my `.gitlab-ci.yml`:

```yaml
image: clojure:lein-2.8.1

pages:
  script:
  - lein run
  - mkdir public
  - mv resources/public/blog/* public
  artifacts:
    paths:
    - public
  only:
  - master
```

P.S.: on a side note, I might be interested to try working on #74, is someone already working on it? Is there still interest to have a recommender system implemented in Cryogen? (You can move the discussion about this on the proper issue if you feel like it and close this issue, otherwise if you answer here I'll close the issue myself 😃)

**Comment by lacarmen** [comment]
No worries, I'm glad you got it working! 

I don't think anyone is working on #74 so if you're interested then go for it! And don't hesitate to reach out if you have questions. :)
