### ISSUE TITLE
Generating CNAME file during compilation

### ISSUE THREAD

**Issue by Sudha247** [cryogen-project/cryogen#170]
My site is hosted on GitHub pages with a custom domain. Every time I run `lein run` or `lein ring server`, the CNAME file gets deleted. Is there anyway I could generate it every time I execute the commands?
I have the right url in the `config.edn` file.

**Comment by lacarmen** [comment]
Take a look at the end of the [GitHub pages deployment docs](http://cryogenweb.org/docs/deploying-to-github-pages.html). You can add the CNAME file to your resources and have it copied over to the public folder you can keep it in your public folder and add `CNAME` to your list of `keep-files` in your config.

**Comment by Sudha247** [comment]
Alright. Thanks a lot!
My bad, I didn't read it before.
