### ISSUE TITLE
Anchors landing controls for theme with fixed header

### ISSUE THREAD

**Issue by fahdkh** [cryogen-project/cryogen#171]
I have a fixed header at the top in theme which breaks the anchors landing for list created with toc. I want to do something like this.
`<span id="anchorID" class="anchor"></span>`
` <h2>Heading to be anchored</h2>`
 
`.anchor {
    display:block;
    padding-top:100px;
    margin-top:-100px;
    visibility:hidden;
 }`

This would enable anchor landing position control depending on the header size. Could you tell me how can I fix this?

Cryogen is awesome!

**Comment by lacarmen** [comment]
This is how I fixed the anchor positions in another project of mine:

```
.section::before {
    display: block;
    content: " ";
    margin-top: -95px;
    height: 95px;
    visibility: hidden;
    pointer-events: none;
}
```

**Comment by fahdkh** [comment]
Thank you. This worked as well! I don't have much experience with frontend yet.
