### ISSUE TITLE
Issue with generated links to css and js files.

### ISSUE THREAD

**Issue by bradlucas** [cryogen-project/cryogen#172]
There looks to be a breaking change between the versions 0.1.62 and 0.1.63 of cryogen-core. The issue is the links generated to style and script blocks on pages which are not at the root level.

To verify the issue you can follow the directions to build a `my-blog` project. Create this project which will include 0.1.63 of cryogen-core. Then run `lein ring server` and navigate to the Archives page. You'll notice the formatting will not match the home page. If you inspect the page you'll see the main screen.css page's link looks like this:

```
<link href="css/screen.css" rel="stylesheet" type="text/css">
```

Now, go and edit the project.clj file and change the version of cryogen-core to the previous version, 0.1.62 and restart the ring server. Navigate to the Archives page you'll notice it has the same look as the home page. The link here will be:

```
<link href="/blog/css/screen.css" rel="stylesheet" type="text/css">
```

I notice that the Javascript includes have the same issue. 

I did look around a bit to see what changed between 62 and 63 and don't see all that much changed. I am curious about the version change of the included selmer library from 1.11.2 to 1.12.2.

Could this be something?

**Comment by yogthos** [comment]
Ah looks like the issue is due to the [change in version 1.12.1](https://github.com/yogthos/Selmer/blob/master/changes.md) where `:servlet-context` was renamed to `:selmer/context`. The [compiler](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj) namespace in cryogen-core needs to be updated to match.

**Comment by yogthos** [comment]
I just pushed out a fix, let me know if it looks good to you.

**Comment by bradlucas** [comment]
Looks and works great. I did the test above using your latest version 0.1.64 and the issue is gone.

Thanks very much for fixing it.
