### ISSUE TITLE
Solution for compiled JS assets

### ISSUE THREAD

**Issue by devth** [cryogen-project/cryogen#173]
Would be great if there was a way to consume JS deps from NPM, transpile them down to ES5 (babel?) and minify them (webpack?).

Not sure if it makes more sense to use CLJS for this or Webpack + Babel.

**Comment by lacarmen** [comment]
While I like the idea, I'm not a JS dev so I'm not familiar with the ecosystem at all and wouldn't be able to maintain it. 

You could try to achieve the same effect by having a watcher for your JS files output to an asset directory that cryogen watches.

**Comment by devth** [comment]
Sure. I can setup a web pack build locally in my project. Just thought it’d be cool if a CLJS pipeline was provided.
