### ISSUE TITLE
Errors with lein-ring

### ISSUE THREAD

**Issue by Alxander64** [cryogen-project/cryogen#177]
https://stackoverflow.com/questions/54810552/lein-ring-failures-under-leiningen-2-9-0

Running either

> lein ring server

or

> lein new cryogen my-blog

Has some issues. Found that upgrading lein-ring plugin in project.clj to 0.12.5 makes it work fine, although the link above mentions things about ring-core and ring-jetty-adapter. Not sure if those need a fix anywhere or if the version bump on lein-ring is sufficient.

**Comment by yogthos** [comment]
Looks like this was caused by outdated dependencies, I've updated the dependencies in the project and the new release should work with the latest lein.
