### ISSUE TITLE
IndieWeb integrations?

### ISSUE THREAD

**Issue by coreagile** [cryogen-project/cryogen#182]
Hi,

I've recently stumbled across the [IndieWeb movement](https://indieweb.org/Getting_Started) and it got me curious -- would the cryogen project benefit from some automatic integration with IndieWeb features like:

- web sign-in
- h-card
- IndieAuth
- MicroFormats
- POSSE

I've had to manually update the theme I'm using (lotus) to have a bunch of the above things, but I might find the energy to make those things more generic and configurable if the project would be amenable!

You can test my site using <https://indiewebify.me/validate-h-card/> and entering <https://www.calmabiding.me>

Thanks so much for this awesome project!

Stephen.

**Comment by lacarmen** [comment]
This seems pretty interesting, but I don't know much about IndieWeb myself. Do you only need to update the markup?

**Comment by coreagile** [comment]
For the most part, yes. There are a few parts like ping backs/webmentions that can’t be done with a purely static site, so I probably wouldn’t worry about including that in cryogen. Though it might be a nice add on to the ring server...

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by lacarmen** [comment]
Cool, cool. So if you're interested in doing a PR then I'd suggest storing all of the configurable values in a map under a top level key `:indie-web` in the config. 

Something like this...

```clojure 
{ 
 :indie-web {:note "Senior Software Engineer Player-Coach"
             :email "mailto:stephen@calmabiding.me"}
}
```

**Comment by coreagile** [comment]
Thanks for the advice!

What about nesting it a bit further? I’m thinking of an :h-card key inside the :indie-web for example. That way we can separate that from other features like indie-auth...

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by lacarmen** [comment]
Yeah, that makes sense. I'll leave it up to you to structure it since
you're more familiar with all the IndieWeb bits. :)

**Comment by coreagile** [comment]
Cool. Thanks! Next time I find some time I’ll start poking around.

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by holyjak** [comment]
It has been over 2 years so I close this for the time being. Anyone interested can re-open and send a PR :)
