### ISSUE TITLE
Bug: Wrong context on some layouts

### ISSUE THREAD

**Issue by ejelome** [cryogen-project/cryogen#185]
Hi great job w/ Cryogen :)

I've recently tried to make a Cryogen theme and found some interesting bugs (mostly unexpected values from each layout context):

1. `author.html` uses `home` as `:active-page` value
    => Expected: `author` to reflect its layout
2. `tag.html` and `tags.html` both uses `tags` as `:active-page` value
    => Expected: `tag` for `tag.html`
3. `home.html` and `previews.html` has `:post` context on `:page` keyword
    => Expected: `:page` should have page-related contexts
4. `toc` seems to start at `h3` downwards and there's no option to change it
    => Expected: Should start at `h2` (or at least have an option to specify starting point)

**Comment by lacarmen** [comment]
Hi, glad you're enjoying the project :) 

1-3 should be easy to fix. I've have to take a closer look to see what's going on with 4. 

Since you're working on a theme, would you be interested in submitting a PR for this?

**Comment by ejelome** [comment]
Hi,

Correct, no. 1 and no. 2 is fixable with `selmer` blocks; no. 3 can just ignore `:page` context. On no. 4; it's really outside any context iirc.

Regarding the theme, sure, I'd gladly send a PR once it's finished :)
