### ISSUE TITLE
How to make cryogen support Latex or MathJax?

### ISSUE THREAD

**Issue by zhaoyul** [cryogen-project/cryogen#188]
Thanks, Love your great work.

**Comment by lacarmen** [comment]
To use MathJax, it looks like all you need to do is include their scripts on your pages and the appropriate HTML (which you would generate from md/asc). Their [getting started docs](https://www.mathjax.org/#gettingstarted) has an [example](http://jsbin.com/?html,output) on jsbin.

**Comment by holyjak** [comment]
Also you can use `pandoc` to process markdown instead of the built-in processor and pandoc supports (La)TeX in .md, it seems.
