### ISSUE TITLE
Preprocess links to open them in the new tab

### ISSUE THREAD

**Issue by zshamrock** [cryogen-project/cryogen#192]
Currently, markdown doesn't allow to specify that link should be opened in the new tab, which means fallback to manual "<a href= target=>" definition instead of markdown syntax. 

Would it be possible to pre-process markdown links and generate the corresponding HTML link tag with the `target=_blank`?

**Comment by lacarmen** [comment]
Cryogen uses markdown-clj by default (you could switch to a different markdown parser), so it might be better to open the issue there. 

Alternatively, you could [customize the parser](https://github.com/yogthos/markdown-clj#customizing-the-parser) to behave how you want. I use the `:replacement-transformers` [here](https://github.com/cryogen-project/cryogen-markdown/blob/master/src/cryogen_markdown/core.clj#L30) to inject the blog prefix in front of image links, so you could do something similar to inject `target=_blank`.

**Comment by zshamrock** [comment]
Thank you, @lacarmen. Will consider then the option to customize the parser indeed. So close this ticket.
