### ISSUE TITLE
Default `:layout` based on posts/pages in the path

### ISSUE THREAD

**Issue by holyjak** [cryogen-project/cryogen#193]
Currently it is required that `:layout` is provided in the metadata of each file. It should not be necessary - it seems logical that all files under `/pages/` default to `:page` and those under `:posts` default to `:post`.

(It would simplify my migration from my Gatsby blog :-))

I can try to make a PR for this if you agree.

**Comment by lacarmen** [comment]
That sounds reasonable to me - as long as you can still change the default 😄 

And a PR would be great! TIA!
