### ISSUE TITLE
Default templates not working / missing `{% block meta %}`

### ISSUE THREAD

**Issue by nickstares** [cryogen-project/cryogen#199]
Hello,

Using the `lein new cryogen` template, it seems that the default themes (other than `blue`) aren't working for me.
E.g.
```
{:theme "nucleus"}
```
gives

```
compiling assets...
compiling sass
copying theme resources
	 themes/nucleus/css --> public/blog/css
	 themes/nucleus/js --> public/blog/js
	 themes/nucleus/html/404.html --> public/blog/404.html
copying resources
	 content/img --> public/blog/img
	 content/md/posts --> public/blog/posts
	 content/md/pages --> public/blog/pages
compiling pages
--> /blog/pages-output/about/
Error: No closing tag found for the tag for template file:themes/nucleus//html/page.html
```

Just by comparing `themes/nucleus/html/page.html`  and `themes/blue/html/page.html`, I noticed that 
```
{% block meta %} 
```
was missing from nucleus before the line `{% if page.description %}`. I added that and it fixed it. Not sure if this is the proper solution but it is a workaround.

**Comment by lacarmen** [comment]
@nickstares Yeah sorry about that, #198 fixes it. But good thing you can just update the templates yourself :)
