### ISSUE TITLE
Cryogen 0.3.x is not working on windows

### ISSUE THREAD

**Issue by chiniara** [cryogen-project/cryogen#204]
Hi, i was trying to make a simple blog but it wasnt working.
After some fiddling i found that changing cryogen.core from version 0.3.1 to 0.2.3 makes it work.
0.3.0 is not working also

This is the error
`Error: resource-path for /html/page.html returned nil, typically means the file doesn't exist in your classpath. `

I could try to help fix it, i would just need some guidance

**Comment by lacarmen** [comment]
@chiniara I believe this is where the bug is coming from https://github.com/cryogen-project/cryogen-core/compare/b14f72458bacda0a515024952075880546bfdf0e..9fc85187eb2f54d0b6b1b6ee496d4935eb9c863e#diff-c402507764497452d2d26369b16dc3deL561

**Comment by chiniara** [comment]
@lacarmen 
Thanks for pointing me to this line.
Actually there is nothing wrogn with Cryogen's code.
I found that the problem resides in Selmer, the 1.12.15 version to be  exact.

This commit :
https://github.com/yogthos/Selmer/commit/1acae051f3d693c98c44b64fead0dc13d7f01a93

It hardcodes the '/' for paths so its breaking windows compatibility.

**Comment by chiniara** [comment]
So just to update this, i wasnt able to fix the problem in selmer so this is still broken and my classes just started so i wont have a lot of free time anymore. If someone else also want to take a look it would be great! I'll try to look into it again later though

**Comment by jarmond** [comment]
This should be fixed in Selmer 1.12.26 by https://github.com/yogthos/Selmer/pull/232.

**Comment by holyjak** [comment]
Selmer has been updated thus closing this one.
