### ISSUE TITLE
:toc no longer generates a table of contents

### ISSUE THREAD

**Issue by ir-regular** [cryogen-project/cryogen#205]
Problem: `:toc` tag for pages and posts no longer works.

Observable in: create a new project based on cryogen template. Home page in default theme should have a table of contents because of `:toc true`, but it doesn't. `post.toc` is empty?

Last dependencies when it worked:

```
[cryogen-markdown "0.1.11"]
[cryogen-core "0.3.0"]
```

No longer works with the following dependencies:

```
[cryogen-flexmark "0.1.0"]
[cryogen-core "0.3.1"]
```

Cannot give you greater details at the moment, since after the dependency update my custom overrides in `cryogen.compiler` are throwing an error (`Error: resource-path for /html/page.html returned nil, typically means the file doesn't exist in your classpath.`), and it'll take me a bit to figure out what causes it.

**Comment by holyjak** [comment]
@ir-regular Are you on Windows? Then you are likely running into #204

**Comment by ir-regular** [comment]
> @ir-regular Are you on Windows? Then you are likely running into #204

Nope, on a mac. Build with no overrides runs ok. Unrelated to ToC problem; sorry for the distraction.

> _Update_: Headings are discovered but filtered out by https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/toc.clj#L54 because none has an ID.

Demo files use markdown, and I also use markdown.

Previous version:

- used https://github.com/yogthos/markdown-clj 
- which has an option to automatically generate anchor links from headings
- which was enabled in integration https://github.com/cryogen-project/cryogen-markdown/blob/master/src/cryogen_markdown/core.clj#L28

Current version:

- uses https://github.com/vsch/flexmark-java
- which provides anchor links as an extension: https://github.com/vsch/flexmark-java/tree/master/flexmark-ext-anchorlink
- which _I am guessing_ was not enabled in the new integration: https://github.com/cryogen-project/cryogen-flexmark/blob/master/src/cryogen_flexmark/core.clj (unless Flexmark does some magic)

My guess is based on:

This issue, where someone describes how they used flexmark in Clojure: https://github.com/vsch/flexmark-java/issues/84 - unless something changed, it looks like the extension needs to be explicitly listed in options, and options passed to parser and builder.

**Comment by ir-regular** [comment]
Solved: at minimum, `HtmlRenderer/GENERATE_HEADER_ID` and `HtmlRenderer/RENDER_HEADER_ID` need to be enabled - will add a PR to the integration package.

**Comment by holyjak** [comment]
Awesome, thanks a lot!
