### ISSUE TITLE
Is setting a redirection map supported?

### ISSUE THREAD

**Issue by Folcon** [cryogen-project/cryogen#211]
And if not is this a desirable feature?

Specifically I have existing pages that are linked in places online and would like to `301` or `302` them as I would like to change my url structure on the blog.

What I don't want is people going to the old url and just getting a 404, I think that that sort of thing happens a bit too often just because people changed their site layout.

So I was thinking that if this doesn't already exist, of defining a map in config.edn keyed to `redirects`:
```clojure
{"posts-output"   :post-root-uri
 "pages-output"   :page-root-uri
 "tags-output"    :tag-root-uri
 "authors-output" :author-root-uri}
```
A keyword maps to the current keyword location rewriting the url.

Alternatively it could just be a string remapping:
```clojure
{"posts-output"   "post"
 "pages-output"   "page"
 "tags-output"    "tag"
 "authors-output" "the-author"}
```

Additionally this could also support wholesale redirects if the entire relative path matches allowing:
```
"my-pinboard"   "https://pinboard.in/u:<username>"
```

Good idea? Totally out of scope?

**Comment by lacarmen** [comment]
I think your map would have to be one level deeper, because if you don't include the keyword how would you know what needs to be written to those directories? So for example:

```
{:post-root-uri   {"posts-output" "posts"}
 :page-root-uri   {"pages-output" "page"}
 :tag-root-uri    {"tags-output" "tag"}
 :author-root-uri {"authors-output "the-author"}
```

Then if you had posts `post-{1,2,3}.md` the compiler would spit out the content pages at `/posts/post-{1,2,3}.html` and redirect pages at `/posts-output/post-{1,2,3}.html`. Not sure what you would do if you then changed the output folder again though. Just add more to the inner map? 

```
{:post-root-uri   {"posts-output" "posts"
                   "posts"        "new-posts"}
 ... }
```

And then end up with redirect pages 

```
/posts-output/post-{1,2,3}.html  => redirect to /posts/ 
/posts/post-{1,2,3}.html         => redirect to /new-posts/
```

Or maybe this should just be handled by your hosting platform so you can do wholesale redirects for entire segments of paths. Let me know your thoughts :)

**Comment by lacarmen** [comment]
And to answer the question in the title - no, not currently supported haha.

**Comment by Folcon** [comment]
I personally would like this to be handled here, as opposed to elsewhere in the chain, though others may disagree =)...  I think it makes everything more portable.

I wasn't thinking for compatibility reasons of messing with existing keys, just if you have an entry `:redirects` in your map, you're requesting that cryogen generate redirects for you.

I'd rather people who don't need this functionality, don't need to care it exists =)...

I'm not certain why you need the additional nesting level?
eg: `config.edn`
```
:post-root-uri     "new-posts"
:redirects
{"posts-output"   :post-root-uri}
```
Says to me, take a mapentry, look at the val, is it a keyword? If it is, look up the value for that keyword in the config, so "new-posts" as you said, generate a redirect from the current mapentry key (`posts-output`) to the new `:post-root-uri`, `new-posts`.

What am I missing? =)...

**Comment by lacarmen** [comment]
> What am I missing? 

You want to all the pages that were previously at `posts-output` to redirect you to `:post-root-uri`, but how do you know what used to be at `posts-output`? It's just a string, you wouldn't know if it was post content or page content (in order to generate the old URLs) :)

**Comment by Folcon** [comment]
Sorry, I may be missing this because I'm not quite aware of how the compiler works under the hood?

I haven't had a chance to do that yet 😊...

I wrote a little draft program to work through my thinking and it appears to get the info needed, so I'm getting the impression that's my understanding gap 😄...
```clojure
(defn gen-direct-redirect [old-source new-source]
  ;; this depends on if we want to do html/js redirect etc...
  (println "\nI will generate a file at" old-source "redirecting to" new-source "saying:")
  (println (str "Hi, you asked to go to <siteurl>/" old-source ", I'm just sending you there! Here is a <link> if you don't automatically redirect.")))

(defn gen-an-internal-redirect [old-source new-source]
  ;; this depends on if we want to do html/js redirect etc...
  (println "    I will generate a file at" old-source "redirecting to" new-source "saying:")
  (println (str "Hi, it looks like you were looking for blog post <siteurl>/" old-source ", that page has been moved to <siteurl>/" new-source ". Here is a <link> if you don't automatically redirect.")))

(defn gen-internal-redirects [old-source new-source written-blog-post-paths]
 (println "\nI will generate a series of redirects at" old-source "redirecting to" new-source)
 (doseq [post-path written-blog-post-paths]
   (gen-an-internal-redirect (str old-source "/" post-path) (str new-source "/" post-path))))

(defn extract-redirects-from-config [{:keys [redirects] :as config} written-blog-post-paths]
  (doseq [[old-source target] redirects]
    (cond
      (keyword? target)
      (gen-internal-redirects old-source (get config target) written-blog-post-paths)

      (string? target)
      (gen-direct-redirect old-source target))))

(def config {:redirects {"posts-output"       :post-root-uri
                         "ancient-posts-path" :post-root-uri
                         "pinboard" "http://pinboard.in/<username>"}
             :post-root-uri "new-posts"})

(def written-blog-post-paths-extracted-from-compilation-process ["hello-world-page.html" "some-other.html"])

(extract-redirects-from-config config written-blog-post-paths-extracted-from-compilation-process)
```

REPL Output:
```
I will generate a series of redirects at posts-output redirecting to new-posts
    I will generate a file at posts-output/hello-world-page.html redirecting to new-posts/hello-world-page.html saying:
Hi, it looks like you were looking for blog post <siteurl>/posts-output/hello-world-page.html, that page has been moved to <siteurl>/new-posts/hello-world-page.html. Here is a <link> if you don't automatically redirect.
    I will generate a file at posts-output/some-other.html redirecting to new-posts/some-other.html saying:
Hi, it looks like you were looking for blog post <siteurl>/posts-output/some-other.html, that page has been moved to <siteurl>/new-posts/some-other.html. Here is a <link> if you don't automatically redirect.

I will generate a series of redirects at ancient-posts-path redirecting to new-posts
    I will generate a file at ancient-posts-path/hello-world-page.html redirecting to new-posts/hello-world-page.html saying:
Hi, it looks like you were looking for blog post <siteurl>/ancient-posts-path/hello-world-page.html, that page has been moved to <siteurl>/new-posts/hello-world-page.html. Here is a <link> if you don't automatically redirect.
    I will generate a file at ancient-posts-path/some-other.html redirecting to new-posts/some-other.html saying:
Hi, it looks like you were looking for blog post <siteurl>/ancient-posts-path/some-other.html, that page has been moved to <siteurl>/new-posts/some-other.html. Here is a <link> if you don't automatically redirect.

I will generate a file at pinboard redirecting to http://pinboard.in/<username> saying:
Hi, you asked to go to <siteurl>/pinboard, I'm just sending you there! Here is a <link> if you don't automatically redirect.
nil
```

Happy to set aside the time to read through the core if that's the piece I'm missing, I definitely want to use cryogen in the long term, so I think it's well worth the time =)...

**Comment by lacarmen** [comment]
Sorry for the late response (been busy over here) but maybe if we walk through the compilation steps it'll help clear things up?

Let's say our config starts out like this 

```
{... 
 :post-root     "posts"
 :post-root-uri "posts-output" 
 ...}
```

And under `content/md/posts/` we have `post-1.md`, `post-2.md` and `post-3.md`. 

When the compiler runs, it knows to look for posts in `content/md/posts` because of `:post-root`, and it knows to output the compiled posts under `public/posts-output/` because of `:post-root-uri`. So we should have 

```
content/md/posts/post-1.md
content/md/posts/post-2.md
content/md/posts/post-3.md

public/posts-output/post-1.html
public/posts-output/post-2.html
public/posts-output/post-3.html
```
---

Now we change the config to the following:

```
{... 
 :post-root     "posts"
 :post-root-uri "new-posts-output" 
 ...}
```

and what the compiler will output is 
```
public/new-posts-output/post-1.html
public/new-posts-output/post-2.html
public/new-posts-output/post-3.html
```

Once we make this config change, the compiler has no idea what `"posts-output"` is. It's not in the config anymore. The compiler can only use what it is provided with at the time of compilation (config, content and themes -- not the public folder. Blowing away the public folder is step 1 of compliation). 

---

So now you want to generate the following redirect pages:
```
public/posts-output/post-1.html  =>  public/new-posts-output/post-1.html
public/posts-output/post-2.html  =>  public/new-posts-output/post-2.html
public/posts-output/post-3.html  =>  public/new-posts-output/post-3.html
```

Say you add `:redirects {"posts-output" "new-posts-output"}` to the config. But what used to be at `"posts-output"`? How do you know what `<thing>.html` to put in the `posts-output` folder? You need the additional key for the compiler to go "oh the **posts** used to be here" 

```
{... 
 :post-root     "posts"
 :post-root-uri "new-posts-output" 
 :redirects     {:post-root-uri {"posts-output" "new-posts-output"}
 ...}
```

**Comment by holyjak** [comment]
How do you want to return 301 or 302 when all you have is a directory with static files, that either are or are not there? The only thing you can do at the Cryogen level is to create a page (returning 200) that contains info about where the page has moved.

I host my blog on Netlify and use [`content/_redirects`](https://docs.netlify.com/routing/redirects/) to configure redirects. This will be different for each static page hosting. (And one of the reasons I prefer Netlify over S3.)

**Comment by Folcon** [comment]
@lacarmen: I've been really lax on this, all I can say is that work has taken up a bit more time than I'd like so I've not had a chance to really give this the attention it's due and for that I apologise.

I've even stopped blogging for the moment :(...

Hopefully my schedule will clear up over the next month or so after which I can sit down and re-read everything and give you a proper response.

@holyjak: I actually have a reasonably quick answer for this that I'll outline below, perhaps it's not the best, so any amendments you can suggest to improve it would be gratefully appreciated =)...

I originally had a plan for this with 2 stages of failover:
1) javascript redirect - https://css-tricks.com/redirect-web-page/#javascript-redirects
2) Just a bit of text saying the url moved and then a link to the new url, which is basically what you're suggesting.

I'm wanted something that means that I can host it on github pages and it just works (default off), without negatively affecting anyone who's using redirects like you're doing.

I just really don't like linkrot, and if I can reduce the frustration of hitting a 404 to content that does legitimately exist, but has been moved I think that's a win =)... I've been bitten a bit too often with that issue.

(I was initially thinking of a http redirect - https://css-tricks.com/redirect-web-page/#html-redirects, but my understanding is that browsers don't always react well to it? So I discarded it.)

**Comment by holyjak** [comment]
Do we need built-in support in Cryogen for this? Couldn't you simply create the redirecting pages yourself, manually? Unless this is a common need, I would prefer not to complicate Cryogen when there already is (a manual) solution.

You can use a babashka script, feeding it a map and gettiing back the html files needed. Just put it into your build pipeline...

**Comment by holyjak** [comment]
What about closing this one as won't fix, @bombaywalla / @lacarmen ?

**Comment by bombaywalla** [comment]
@holyjak Sounds reasonable to me.  Given that there are alternatives.

**Comment by Folcon** [comment]
I'll close it on my side as I've not had much time recently to post stuff so blog things have been pretty low priority.

Your initial suggestion @holyjak with a babashka script merits some testing on my side, but I can do that in my own time =)...
