### ISSUE TITLE
[Feature Request] Provide option to compile sass without external tooling - sass/compass

### ISSUE THREAD

**Issue by ieugen** [cryogen-project/cryogen#214]
For Sass compilation, there is a java wrapper https://github.com/bit3/jsass . 

It uses JNI to call a bundled libsass and compile sass files. 
Using this wrapper will eliminate the need to have external tools installed and make the website easier to build on another machine. 

Also custom processing can be done.

Note: I'm not a front-end dev and this might not be possible if compass offers more than just and interface for calling libsass .

**Comment by lacarmen** [comment]
Compass has been removed from the project so I think this should be fine? I don't use sass myself though so I'm not sure if there's any differences between using the java wrapper and whatever cli tool.

**Comment by KingMob** [comment]
I suspect using jsass would be more complicated than installing standard sass for most people/build tools.

- `libsass`, and projects wrapping it, like jsass, have been deprecated for years now, so there's a higher risk of divergence in behavior, CLI options, and/or bugs
- Doesn't JNI expose us to architecture concerns, i.e., making sure we're using the correct compiled version of libsass?

**Comment by ieugen** [comment]
Thanks @KingMob . I was not up to date with the developments in that area.
jsass is also in maintenance mode so I'm closing this issue.

**Comment by KingMob** [comment]
@ieugen No worries, I think it was worth bringing up and checking out. 

I know I personally ran into issues at one point because my Cryogen theme depends on Sass, and something libsass-based caused breakage a while back, because the CLI options weren't the same.

**Comment by devurandom** [comment]
There is also [lein-sass](https://github.com/yogthos/lein-sass).
