### ISSUE TITLE
Your blog link

### ISSUE THREAD

**Issue by EdwardIII** [cryogen-project/cryogen#222]
Hey, just wanted to leave a note, in the README your blog link `My personal blog` goes to: 

http://carmen.la/

Which looks like a github pages 404 page:

![image](https://user-images.githubusercontent.com/412107/99183034-f0fda400-2730-11eb-801e-7848b39af858.png)

**Comment by lacarmen** [comment]
Well that's awkward 😄 I think I broke it when I didn't renew my GitHub premium subscription! Thanks for the heads up
