### ISSUE TITLE
Serve headless with containerized development environment

### ISSUE THREAD

**Issue by fhdkhan** [cryogen-project/cryogen#227]
Is there any way to tell `lein serve` to not to invoke the browser. This is not feasible for containerized development environment.

**Comment by qdhaiqiang** [comment]
I don’t want it to automatically start the browser, in case frontend is not finished building.
How to try?

**Comment by yogthos** [comment]
You'd have to pass `:open-browser? false` to [ring-server](https://github.com/weavejester/ring-server) that's started [here](https://github.com/cryogen-project/cryogen/blob/d1bc85a353de52f46d30bab7e09901739be47af8/src/leiningen/new/cryogen/src/cryogen/server.clj#L62).

**Comment by qdhaiqiang** [comment]
@yogthos It's the  correct answer, Thanks you very much.

**Comment by holyjak** [comment]
It will be more obvious after https://github.com/cryogen-project/cryogen/pull/242/files#diff-d5ee148a4a9e78dc4dff6a50dc4fd315a461fbbe00592a1512ad34e0ac426951R84 is released.

Closing, since the question has been answered.
