### ISSUE TITLE
How to change the port for `lein serve`

### ISSUE THREAD

**Issue by NobbZ** [cryogen-project/cryogen#232]
I expected changing `{:port 3000}` to `{:port 9800}` would change the port to bind to, though…

Still `lein serve` tries to bind to port 3000 wich is already in used on my system.

**Comment by qdhaiqiang** [comment]
The same requirement.

**Comment by qdhaiqiang** [comment]
@NobbZ You can change in source `src/cryogen/server.clj`

![image](https://user-images.githubusercontent.com/12232338/126305656-0f6bec25-7e97-4ce5-88bd-c3cd04f5b50a.png)

**Comment by NobbZ** [comment]
Yeah I found it myself, though its weird that there is some setting in the generated `project.clj` that is then ignored and needs to be changed somewhere else…

Anyway. For me it was just a short experiment, and I left CLJ

**Comment by holyjak** [comment]
> there is some setting in the generated project.clj that is then ignored 

I do not see such setting in the [generated project.clj](/cryogen-project/cryogen/blob/master/src/leiningen/new/cryogen/project.clj)?!

Anyway, the question seems to be answered so closing for the time being. Feel free to reopen if you have more to say.
