### ISSUE TITLE
`clojure -M:build` exite code

### ISSUE THREAD

**Issue by kwladyka** [cryogen-project/cryogen#236]
`clojure -M:build` should break github actions (and other CI/CD) steps when exception is thrown. For example when template has a bug and Selmer try to `date` wrong data format.
In other words `clojure -M:build` should have different exit code, than `0`.

The issue is CI/CD think build succeed and deploy damaged page.

**Comment by holyjak** [comment]
Duplicate of cryogen-project/cryogen-core#134 Contributions appreciated! :)
