### ISSUE TITLE
Doc: "full build" is only mentioned in the end.

### ISSUE THREAD

**Issue by jgomo3** [cryogen-project/cryogen#239]
Maybe the documentation doesn't mention `lein run` until the last article "Fast Compilation", where it says "make sure to make a full build (f.ex. via lein run) before publishing your site".

Maybe I missed it. The fact is that I was trying to find a command for only "building" the `public` folder, as I've been using the `lein ring serve` for that purpose; and I didn't find it until that last section.

It would be nice to find a place in the "deploying" or "publishing" sections where an explicit instruction to "build" is expressed.

And now that you are supporting both lein and Clojure CLI, that instruction should go for both.

**Comment by yogthos** [comment]
Good idea. I've documented doing a single build in the quick start section [here](https://github.com/cryogen-project/cryogen-docs/blob/master/content/md/docs/getting-started.md).

**Comment by holyjak** [comment]
@yogthos can we close this one? If not, what remains to be done?

**Comment by holyjak** [comment]
This https://github.com/cryogen-project/cryogen/pull/242/commits/65b39b3785259adbf6e462e9a51143e243a6e04d is also making it clearer in the generated docs post, so I think that is sufficient.
