### ISSUE TITLE
RSS feed: only publishes article's "summary"

### ISSUE THREAD

**Issue by allentiak** [cryogen-project/cryogen#241]
I'm trying to publish the posts from my blog https://allentiak.github.io/ into the blog aggregator https://planet.debian.org/

However, instead of the full post, only the first paragraph is posted. It seems the RSS generator assumes the first paragraph from my post is the article summary, and only publishes that?

This is how my article looks in the aggregator:

![RSS-bug--planet](https://user-images.githubusercontent.com/1922297/130006236-3b89e6ff-bfea-4db9-8e91-58eadd3af2c6.png)

Is this the normal behavior, or a bug?
If this is the normal behavior, is there a specific configuration I'm missing so I can change it?

RSS link sent to the aggregator: https://allentiak.github.io/feed.xml
Blog Source: https://github.com/allentiak/website-source--cryogen
Blog Binary: https://github.com/allentiak/allentiak.github.io

**Comment by holyjak** [comment]
That is working as designed. You can change what is included using `<!--more-->`, see http://cryogenweb.org/docs/configuration.html and `blocks-per-preview`.

You could workaround this limitation by setting blocks-per-preview to a really high number or by always including `<!--more-->` at the very end. 

What would you want to include anyway? HTML? Plain text?

**Comment by allentiak** [comment]
> That is working as designed.

I see.
Thanks for your answer!


>  You could workaround this limitation by [...] always including  at the very end.

That's a great hint! Thanks!
I'll definitely use it, as it seems extremely flexible.


> What would you want to include anyway? HTML? Plain text?

Both.
I published my website into a "planet-like" aggregator website, and it expects the full article (contrary to its preview) to be displayed.

As a workaround, I used a <![CDATA[...]]> block ;-)
