### ISSUE TITLE
deps-new error when creating a new site

### ISSUE THREAD

**Issue by cap10morgan** [cryogen-project/cryogen#248]
When I run `clojure -Sdeps '{:deps {io.github.cryogen-project/cryogen {:git/tag "0.6.6" :git/sha "fcb2833"}}}' -Tnew :template org.cryogenweb/new :name my/website` after installing deps-new 0.4.3 as a tool named `new` (just like in your instructions; `clojure -Ttools install com.github.seancorfield/deps-new '{:git/tag "v0.4.3"}' :as new`) I get the following error and no site directory is created:

`No function found on command line or in :exec-fn`

This is with Clojure CLI 1.10.3.1040

**Comment by seancorfield** [comment]
It should be:

```bash
clojure -Sdeps '{:deps {io.github.cryogen-project/cryogen {:git/tag "0.6.6" :git/sha "fcb2833"}}}' -Tnew create :template org.cryogenweb/new :name my/website
```

`create` is missing.

**Comment by yogthos** [comment]
thanks for the fix 👍
