### ISSUE TITLE
Cryogen does not list as a clojure project

### ISSUE THREAD

**Issue by LiGoldragon** [cryogen-project/cryogen#261]
Since cryogen is mostly html, it doesn't show up when searching for `language:clojure static site`. I found it by accident, by searching `clojure static site`. I had been looking for months, but never saw cryogen until now. You could put the html in a different repo or branch.

**Comment by lispwright** [comment]
The author and users of Cryogen seems to be doing something right.

Before checking the issues I started with "clojure static site generator" and Brave Search provided it as the first result.  Now Bing and Google the same.  Just got started on this without too much input to search personalization besides lots of mostly Brave searches on Clojure stuff so these are probably pretty generic results.

That said, then trying "language:clojure static site" to Google provided Cryogen as the 3rd result after https://nickgeorge.net/programming/custom-static-clojure-websites-an-update/ (a build your own with Stasis) and a gaggle of Reddit results, I expect some degree of personalization is possible in that result.  Fifth results is the couple of years old https://medium.com/pragmatic-programmers/cryogen-static-site-generation-made-easy-2803502397bf

**Comment by LiGoldragon** [comment]
That's a way to search GitHub.
