### ISSUE TITLE
Feature request: Tag-specific RSS feeds

### ISSUE THREAD

**Issue by mwfogleman** [cryogen-project/cryogen#44]
I'd like to add my blog to several topic-specific planets, but they require curated RSS feeds (e.g. the Clojure planet requires only Clojure-related posts). Could Cryogen support this?

**Comment by lacarmen** [comment]
This should definitely be possible. I could add something like `:filtered-rss ["clojure"]` to the config file and generate curated RSS feeds based on that along with the main RSS feed that's currently being generated.

**Comment by mwfogleman** [comment]
Great, thanks Carmen!

For those of you in the cheap seats, if you are waiting for this to be a feature, you can use Yahoo Pipes to filter the default, inclusive RSS feed.

**Comment by lacarmen** [comment]
Should be done with version 0.1.12 of cryogen-core now :) 

You would have to add `:rss-filters ["clojure"]` to your `config.edn` and of course the filters you list have to match the tags that you're using in your posts. The generated xml files will be named after the tags.

**Comment by mwfogleman** [comment]
Wow! I did not expect same-day turnover-- thanks Carmen! Keep up the good work! :+1:

**Comment by mwfogleman** [comment]
Carmen,

Not sure how I didn't notice until now, but using this feature on my install generates RSS feeds with only the titles and the links.

https://mwfogleman.github.io/Clojure.xml
https://mwfogleman.github.io/Emacs.xml

I did do a hairy upgrade, so it's possible I messed things up.

**Comment by lacarmen** [comment]
So I was using `(get posts-by-tags filter)` to get the posts for each filter, but it turns out `posts-by-tags` only contained the `:uri` and `:title` keys since I originally made that variable for making tag pages.

I've added in the `:content` key and tested so the filtered rss feeds to get generated properly now. Just bump up cryogen-core to 0.1.19 :)

**Comment by mwfogleman** [comment]
Great, thanks so much Carmen.

I took a peek at the bugfix commit- neat to see how this functionality (and presumably much of Cryogen) is implemented with core functions like select-keys, get, reduce, etc. :D
