### ISSUE TITLE
Could you switch to iso8601 / rfc3339 dates for the blog entries?

### ISSUE THREAD

**Issue by mathiasp** [cryogen-project/cryogen#46]
a) this is the only unambiguous date notation. No need to for meta information.
    There is no yyyy-dd-MM notation...
b) it sorts much nicer in the file system
c) dd-MM-yyyy is not very common. It's allmost only used in continental europe. And even there it's old-school since 1992, when iso8601 was included in EN 28601. Since then numerical dates should follow the yyyy-MM-dd form, only alphanumerical dates shall use the old form (e.g. 1. Mai 1992 in Germany).

**Comment by yogthos** [comment]
:+1:

**Comment by led** [comment]
http://xkcd.com/1179/

**Comment by lacarmen** [comment]
There's a config value for the date format in `config.edn` which defaults to ISO8601 if it's `nil` but I guess I should just get rid of it and use the ISO format by default.

**Comment by yogthos** [comment]
I'd keep the config option and just change the default.

**Comment by lacarmen** [comment]
But the default is already yyyy-MM-dd

**Comment by j0ni** [comment]
@lacarmen that's true, but the [default `config.edn`](https://github.com/lacarmen/cryogen/blob/master/src/leiningen/new/cryogen/config.edn#L12) overwrites that default.

**Comment by lacarmen** [comment]
Ah, I misunderstood. Yes, I'll change that value to nil when I get the chance :)
