### ISSUE TITLE
Date is not parsed correctly

### ISSUE THREAD

**Issue by infiniteiteration** [cryogen-project/cryogen#54]
I've set `:post-date-format "yyyy-MM-dd"` and have post names like `2013-02-10-backbone-object-creation.md` but it is rendered as _4. August 0015_ ..

**Comment by lacarmen** [comment]
I can't seem to reproduce the bug. Which version of `cryogen-core` are you using in your project?

**Comment by infiniteiteration** [comment]
I used an about a two month old cryogen, now returned to it.. After using a new version it works fine. It's a bit misleading though that the newly generated template contains posts with `dd-mm-yyyy` format.

Closing this issue as it works now. Thank you!

**Comment by lacarmen** [comment]
Looks like I didn't rename all the posts correctly. I'll fix that later today :)

**Comment by dl1ely** [comment]
Was fixed with PR #53, nothing more to do here.
