### ISSUE TITLE
Read cryogen selmer layouts?

### ISSUE THREAD

**Issue by kwladyka** [cryogen-project/cryogen#56]
Hi,

I am sorry, but i can't find any ready layouts to download from the Internet and i believe more people like me are looking layouts for cryogen, so mayby my question will be helpful also for others.

So my question is: Where can i find ready layouts to use with cryogen? Or they just don't exist? :) If they exist somewhere deep in the Internet maybe it is worth to mention about that in doc.

**Comment by lacarmen** [comment]
I only have the two [here](https://github.com/lacarmen/cryogen-templates) for the moment. One of them is the current default that comes with Cryogen. 

Unfortunately I won't have time to add more layouts for a month or so. I'm open to submissions though :)

**Comment by kwladyka** [comment]
Or maybe can i find somewhere "selmer layouts" and modify to "cryogen layouts"? I didn't find any.

**Comment by lacarmen** [comment]
No you can't really do that. You can however, find a blog template that you like and take the css and html and edit one of the existing cryogen templates

**Comment by yogthos** [comment]
One of the features we'd like to add is the ability to create layouts. That would first require to pull out any inline variables in the templates into config though. Once that's done it should be pretty easy to add functionality to specify the layout folder and use the files from there.
