### ISSUE TITLE
Add option for Stylus support

### ISSUE THREAD

**Issue by MortalCatalyst** [cryogen-project/cryogen#57]
Would an option to use Stylus instead of sass scss. it just avoids the requirement of installing ruby just to get sass.

**Comment by markokocic** [comment]
I am pretty sure that I used Cryogenweb before without having sass, but it started failing recently.
Maybe config option not to use any css generator would be useful.

**Comment by lacarmen** [comment]
@markokocic If you are having trouble running Cryogen then please open a separate issue.

**Comment by holyjak** [comment]
Sass is optional. The latest incarnation of sass has a standalone binary - see https://sass-lang.com/install

Closing this issue for now, as the main problem it refers to is not a problem anymore.
