### ISSUE TITLE
 EOF while reading string, : \

### ISSUE THREAD

**Issue by MortalCatalyst** [cryogen-project/cryogen#58]
My apologies if this isn't your issue but this is my first cryogen blog. I cannot see any errors that I have made but keep receiving the below error.

I notice that in the error its compiling User as C:\Users: \sayth\ is it this incorrect path separate with : \ that's the issue if so how can I fix?

java.lang.RuntimeExceptionException in thread "main" java.lang.RuntimeException: EOF while reading string, compiling:(C:\Users: \sayth\AppData\Local\Temp\form-init627878547038619336.clj:1:106)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)

**Comment by lacarmen** [comment]
I wrote cryogen for *nix machines so I think it's the back slash messing around with the parsing. I'll have to take a look later.

**Comment by yogthos** [comment]
@MortalCatalyst could you paste the entire stack trace, it's not evident what specifically is causing the error from the snippet.

**Comment by MortalCatalyst** [comment]
C:\Users\sayth\Repos\cryogen>lein ring server
loading module: Markdown parser
compiling assets...
java.lang.RuntimeException: EOF while reading string
           clojure.lang.Util.runtimeException                         Util.java:  221
  clojure.lang.LispReader$StringReader.invoke                   LispReader.java:  451
    clojure.lang.LispReader.readDelimitedList                   LispReader.java: 1138
     clojure.lang.LispReader$MapReader.invoke                   LispReader.java: 1081
                 clojure.lang.LispReader.read                   LispReader.java:  183
                   clojure.lang.RT.readString                           RT.java: 1737
                     clojure.core/read-string                          core.clj: 3497
            cryogen-core.compiler/read-config                      compiler.clj:  268
         cryogen-core.compiler/compile-assets                      compiler.clj:  286
cryogen-core.compiler/compile-assets-timed/fn                      compiler.clj:  326
   cryogen-core.compiler/compile-assets-timed                      compiler.clj:  325
                          cryogen.server/init                        server.clj:   11
                      clojure.lang.Var.invoke                          Var.java:  375
                 ring.server.standalone/serve                    standalone.clj:   95
                   clojure.lang.RestFn.invoke                       RestFn.java:  423
                  ring.server.leiningen/serve                     leiningen.clj:   21
                               user/eval13059  form-init1648981584556670792.clj:    1
                   clojure.lang.Compiler.eval                     Compiler.java: 6703
                   clojure.lang.Compiler.eval                     Compiler.java: 6693
                   clojure.lang.Compiler.load                     Compiler.java: 7130
               clojure.lang.Compiler.loadFile           Exception in thread "main"           Compiler.java: 7086
                     clojure.main/load-script                          main.clj:  274
                        clojure.main/init-opt  java.lang.RuntimeException: EOF while reading string, compiling:(C:\Users\sayth\AppData\Local\Temp\form-init1648981584556670792.clj:1:107)
        at clojure.lang.Compiler.load(Compiler.java:7142)
                        main.clj:  279  at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)

                        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
clojure.main/   at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: EOF while reading string
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.LispReader$StringReader.invoke(LispReader.java:451)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
initialize      at clojure.lang.LispReader$MapReader.invoke(LispRe  ader.java:1081)
        at clojure.lang.LispReader.read(LispReader.java:183)
        at clojure.lang.RT.readString(RT.java:1737)
        at clojure.core$read_string.invoke(core.clj:3497)
        at cryogen_core.compiler$read_config.invoke(compiler.clj:268)
                        main.clj:  307  at cryogen.server$init.invoke(server.clj:12)
        at clojure.lang.Var.invoke(Var.java:375)
        at ring.server.standalone$serve.doInvoke(standalone.clj:95)
        at clojure.lang.RestFn.invoke(RestFn.java:423)

                                at ring.server.leiningen$serve.invoke(leiningen.clj:21)
        at user$eval13059.invoke(form-init1648981584556670792.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
clojure.main/   at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 11 more
null-opt                          main.clj:  342
                            clojure.main/main                          main.clj:  420
                   clojure.lang.RestFn.invoke                       RestFn.java:  421
                      clojure.lang.Var.invoke                          Var.java:  383
               clojure.lang.AFn.applyToHelper                          AFn.java:  156
                     clojure.lang.Var.applyTo                          Var.java:  700
                            clojure.main.main                         main.java:   37
"Elapsed time: 171.457513 msecs"
Subprocess failed
C:\Users\sayth\Repos\cryogen>

**Comment by yogthos** [comment]
From the error it appears that there is a syntax error in your `resources/templates/config.edn` file.

**Comment by MortalCatalyst** [comment]
{:site-title       "Data Science Blog"
 :author           "Sayth"
 :description      "Covering journey through Data Science "
 :site-url         "http://mortalcatalyst.github.io/""
 :root             "posts"
 :tag-root         "tags"
 :page-root        "pages"
 :blog-prefix      ""
 :rss-name         "feed.xml"
 :rss-filters      ["cryogen"]
 :recent-posts     3
 :post-date-format "dd-MM-yyyy"
 :sass-src         nil
 :sass-dest        nil
 :resources        ["css" "js" "html"]
 :keep-files       [".git"]
 :disqus?          true
 :disqus-shortname "flebber"
 :ignored-files    []

**Comment by yogthos** [comment]
you're missing the closing `}`

**Comment by MortalCatalyst** [comment]
I fixed it and tried again but still getting a similar error. Might try a new project with no changes and see if error occurs

**Comment by yogthos** [comment]
that's probably a good idea

**Comment by MortalCatalyst** [comment]
Thanks for the help. Yes a default site works.
