### ISSUE TITLE
MathJax

### ISSUE THREAD

**Issue by Jesse-Millwood** [cryogen-project/cryogen#59]
I am new to Clojure and webpages for that matter but I was wondering if there is any support for using MathJax or something similar with Cryogen.

Thanks!

**Comment by yogthos** [comment]
At the moment it looks like the syntax is not compatible with the markdown parser used. It should work using the AsciiDoc syntax if you add the js in `resources/templates/html/base.html`

```xml
<script type="text/javascript"
  src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

**Comment by Jesse-Millwood** [comment]
Thanks for the quick response!
I had tried adding it in a markdown file, makes sense why it didn't work then

**Comment by yogthos** [comment]
you'd have to add `[cryogen-asciidoc "0.1.1"]` in your `project.clj` under `:dependencies` to enable it

```clojure
:dependencies [[org.clojure/clojure "1.6.0"]
                           [ring/ring-devel "1.3.2"]
                           [compojure "1.3.2"]
                           [ring-server "0.4.0"]
                           [cryogen-asciidoc "0.1.1"]
                           [cryogen-markdown "0.1.1"]
                           [cryogen-core "0.1.21"]]
```

Then you have to put your posts under `resources/templates/asc/posts` ending with the `.asc` extension, eg: `resources/templates/asc/posts/2014-10-10-adoc-post.asc`

**Comment by Jesse-Millwood** [comment]
Thanks for the tip!

**Comment by Jesse-Millwood** [comment]
Turns out that if you include
```html
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']],
                       displayMath: [['\\[','\\]'], ['$$','$$']]}});
 </script>
 <script type="text/javascript"
      src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
 </script>
```
to the `head` tag in `/resources/templates/html/base.html` you can use MathJax in line or as separate centered equations inside of the markdown files
