### ISSUE TITLE
Sub-folders in pages?

### ISSUE THREAD

**Issue by hlship** [cryogen-project/cryogen#60]
I created a sub-folder of pages:

    resources/templates/pages/asc/pages/auth/auth.asc

However, the output was:

    resources/public/pages/auth.html

It is somewhat important to me to keep the folder structure.  Is this behavior a bug, or intentional?

**Comment by lacarmen** [comment]
This is intentional. The compiler concatenates "resources/public" with the `blog-prefix` and the `page-root` from `config.edn` followed by the file name.

**Comment by hlship** [comment]
I'm working on a patch that keeps track of the relative path under resources/templates/pages/asc (or md) and uses that when creating URLs, folders, etc.

**Comment by lacarmen** [comment]
I'm going to close this since, as I said, this behaviour is intentional. Also, I noticed you've made a lot of changes in your fork and not all of them are changes that I'd like to make in my branch.

**Comment by hlship** [comment]
I've ended up forking the ideas for Cryogen, but not any of the code. And my principal use-case is publishing pages (not blogging) in the context of documenting a set of REST APIs.  Thanks for the initial direction, and good luck!
