### ISSUE TITLE
empty img folder will be discarded from git commit

### ISSUE THREAD

**Issue by sveri** [cryogen-project/cryogen#61]
When cloning into another folder there is no resources\templates\img folder available which leads to an error during assets generation.

I guess a simple .keep file in img folder is enough. Or maybe create the img folder if it is non-existent during asset generation.
Or maybe just don't load anything from the img folder if it does not exist.

**Comment by lacarmen** [comment]
>  When cloning into another folder there is no resources\templates\img folder available

There is definitely an `img` folder created when you run `lein new cryogen my-blog`. I'm not sure if that's what you mean by cloning though.

But the fact that an error is being thrown when `"img"` is specified under `:resources` in the config when no `img` folder exists is intentional.

**Comment by sveri** [comment]
Sorry for being not exact enough. This is my workflow.
1. Create new project with lein new cryogen foo
2. Generate some posts
3. Commit everything to github
4. Clone from github and serve them
---- up to here everything is ok

5. Now I clone the repo to a different location (working on a different device) 
6. Add some posts

And here the generation of the static files fail, because of the missing **img** folder.

Does that make sense?

**Comment by lacarmen** [comment]
Yes, thanks for clarifying.

I don't plan on removing the error. It does not stop the auto-compiler, so if you were to add am `img` folder after seeing that error then it would continue with no problem.

Alternatively, just remove `"img"` from the list of resources in the `config.edn` file if you don't plan on putting anything into the `img` folder.

**Comment by sveri** [comment]
Ok, thanks for being clear, didn't know about the config. However, good work you have done here. I really enjoy it so far :-)
