### ISSUE TITLE
[bug] toc

### ISSUE THREAD

**Issue by kwladyka** [cryogen-project/cryogen#62]
```markdown
### Hiccup
### Enlive
### Selmer
## Conclusion
```

produce

```html
<ol class="contents">
<li><a href="#hiccup">Hiccup</a></li>
<li><a href="#enlive">Enlive</a></li>
<li><a href="#selmer">Selmer</a></li>
</ol>

<li><a href="#conclusion">Conclusion</a></li>
```

Please notice ```<li><a href="#conclusion">Conclusion</a></li>``` is outside any ```ol``` or ```ul``` tag.

Why somebody want start with h3 and later has h2? The answer is simple. The title of post is h2 and this is not included in toc (this is good). But to consequence i want have on site:
h2 - post title
h3 - some points
h2 - some things like conclusion

**Comment by lacarmen** [comment]
I'm not sure what you're asking. The TOC is supposed to have a nested structure which is why the conclusion is outside of any ol/ul tag.

**Comment by kwladyka** [comment]
The bug appear only if start with lower H tag then other is post. For example H3 and later in post use H2, or H2 and later is post use H1.

So it should looks like:
```html
<ol class="contents">
  <ol class="contents">
  <li><a href="#hiccup">Hiccup</a></li>
  <li><a href="#enlive">Enlive</a></li>
  <li><a href="#selmer">Selmer</a></li>
  </ol>

<li><a href="#conclusion">Conclusion</a></li>
</ol>
```

or something like that.

But now it is ```<li><a href="#conclusion">Conclusion</a></li>``` after <ol> and in the middle of not list tag.

**Comment by lacarmen** [comment]
So it looks like the nested contents is working properly but it's missing the outside `<ol>` wrapper. I can't see the problem immediately in the [code](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/toc.clj#L21) and I don't have the time to dig deeper right now but if you'd like to submit a pull request I would appreciate that.

**Comment by Artiavis** [comment]
@nezdelion although I think this is *a fix* for the issue, I don't know whether it produces the (presumably) *desired behavior *: later, higher-level headers living at the same indentation level as the earlier, lower-level headers.

Compare:

<ul>
<ul>
<li>Hiccup</li>
<li>Enlive</li>
<li>Selmer</li>
</ul>
<li>Conclusion</li>
</ul>

to

- Hiccup
- Enlive
- Selmer
- Conclusion 

@lacarmen and @kwladyka, which do you see as more reasonable defaults? I, too, have a PR for this issue, but which produces the latter behavior instead of the former.

**Comment by kwladyka** [comment]
@Artiavis i tried to fix it and i found where is the bug. Bug is in algorithm definition, not mistake in code. Algorithm doesn't expect situation like that. So to fix it somebody have to change whole function. But during that i realized it is easier to show that on the same level of ol, then fix it. It mean fix it wasn't so important. It is just nice to have with low priority.

So now i am starting with H2 and later use H3. It is ok :)
