### ISSUE TITLE
[rfe] Support Jade markup

### ISSUE THREAD

**Issue by MicahElliott** [cryogen-project/cryogen#64]
Asciidoc is already a really compelling feature of cryogen, but having Jade [(clj-jade)](https://github.com/ryangreenhall/clj-jade) would be even better for pages needing richer design. Seems this could be cleanly added as another module.

**Comment by yogthos** [comment]
:+1:

**Comment by holyjak** [comment]
None of us maintainers is going to implement it so I will close this now. However we more than welcome any interested user to create the integration, and can advice on how to make it work with Cryogen. The first step is to make the rendering plugin itself, which needs to reify Markup - see https://github.com/cryogen-project/cryogen-markdown/blob/master/src/cryogen_markdown/core.clj#L18
