### ISSUE TITLE
Add "Read More" snippet/elision support

### ISSUE THREAD

**Issue by MicahElliott** [cryogen-project/cryogen#65]
A "Read More/Continue Reading" cutoff ([example](http://brandonhilkert.com/)) saves the landing page from simply becoming your most recent (sometimes long) post. An alternative is to make the archive page your landing ([example](http://quaran.to/)). But I believe it's most desirable to have the top matter (abstracts) from ~5 posts comprise the landing page. Then the bottom of the page could have a link to the archive instead of the next article ([example](http://rsms.me/)).

This seems to be often done with a simple `<!-- more -->` comment marker right in each post. This is trivial in Markdown, and in Asciidoc one just needs to insert 3 lines:

    ++++
    
    ++++

This should be a simple matter for the blogger to just place a "snippet" for-loop in `base.html`. So the real change here is to have the engine cut and store snippets in the generated `index.html` for each compile.

A bit of care might be taken to not include Asciidoc TOCs in the snippet. Maybe the blogger should just not use TOCs. But hopefully it's easy enough to detect/remove the `<ol class="contents">` section. Even better would be to have TOCs come after the `more` marker. This gives the feel of each post having an "Abstract" at the top, which is also the snippet.

Summary: support post snippets, and place N (default ~5) snippets on the home page.

**Comment by lacarmen** [comment]
This was actually brought up yesterday in [this](https://github.com/cryogen-project/cryogen-core/issues/28) `cryogen-core` issue. I'll leave this one open as a reminder though because you've brought up some good points about the TOC that weren't mentioned in the other issue.

**Comment by lacarmen** [comment]
Going to close this one to avoid duplicate entries. A link to this issue exists in the `cryogen-core` issue that I mentioned above
