### ISSUE TITLE
In default theme, on small screen widths, title overflows container [bug]

### ISSUE THREAD

**Issue by mingp** [cryogen-project/cryogen#68]
I just created a new Cryogen project with `lein new cryogen foobar` and then ran the development server with `lein ring server` inside the project directory. (I believe this gets me the latest versions of the relevant dependencies.) Attached are screenshots from Mac OSX Yosemite + Chrome latest.

![image](https://cloud.githubusercontent.com/assets/6671527/8830580/f49bcc1c-306a-11e5-9a0e-1cab13bbff9a.png)

![image](https://cloud.githubusercontent.com/assets/6671527/8830584/fa70f75c-306a-11e5-81a6-6ab223e786ab.png)

The large screen width (desktop-ish) appears to render as expected. The small screen width (mobile phone-ish) appears to have a styling bug where the title text is overflowing the menu bar container in the case of drop-down letters like `y` and `g`.

I think the simplest fix would just be to increase the mobile nav height, possibly to the same as the desktop one.

What do others think? If desired, I can put together a pull request with this change.

Thanks!

**Comment by mingp** [comment]
P. S. Apologies for the wall-of-screenshots. I wouldn't have included the full page screenshots if I had realized they'd take up so much space.

**Comment by mingp** [comment]
EDIT: Updated the original post with smaller images showing only the relevant sections.

**Comment by lacarmen** [comment]
I think it would be simpler to just make the title font smaller in the media queries inside the CSS. Messing around with navbar heights has been a pain in my past experiences.

**Comment by mingp** [comment]
In that case, I think I should remove some spacing off the top as well.

Anyway, I have work soon, but I can probably fiddle around with it a bit afterward. For testing purposes, how would I convince `lein` to use my local version rather than what's in the Maven repository?

Thanks!

**Comment by lacarmen** [comment]
You can do `lein install` to install the template locally :)
