### ISSUE TITLE
Support for content tags in RSS feed

### ISSUE THREAD

**Issue by sanel** [cryogen-project/cryogen#71]
I noticed that Cryogen, when export posts to RSS, does not export tags. RSS spec support this (it is called *category*) and [here](http://www.rssboard.org/rss-specification#optionalChannelElements) is the relevant part.

For example, Blogger is using this form for putting tags:

```
<category scheme="http://www.blogger.com/atom/ns#" term="TAG1"/>
<category scheme="http://www.blogger.com/atom/ns#" term="TAG2"/>
...
```
and WordPress more standarized form like:

```
<category>TAG1</category>
<category>TAG2</category>
```

I'm using tags extensively to generate news on my other site; the script would scrape daily blog feeds searching for the new posts with specific tag and when found, would fetch the title and body, generating news.

Also, RSS readers will benefit from this too since they can order content based on category data, especially if there is significant number of feeds.

What do you think about this option?

**Comment by lacarmen** [comment]
Makes sense to me. If you'd like to make a PR for it, the relevant file is [here](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/rss.clj). Otherwise I'll add it in sometime this week.

**Comment by sanel** [comment]
Thanks for pointers.

Not sure is it me (so I can's see obvious thing maybe) but looks like `clj-rss` does not support setting multiple same tags. Ideally, in `posts-to-items` this could be used:

```clojure
{:guid        link
 :link        link
 :title       title
 :description content
 :category    ["CAT1" "CAT2"]
 :pubDate     date}
```
but `clj-rss` will produce `category` tag with this:

```html
<category>
CAT1
CAT2
</category>
```
instead of:

```html
<category>CAT1</category>
<category>CAT2</category>
```
Do you know any hidden gem to circumvent this issue?

**Comment by lacarmen** [comment]
Probably something for @yogthos to look at since it's his `clj-rss` library :)

**Comment by yogthos** [comment]
@sanel ok just pushed out clj-rss `0.2.0` that supports repeating tags, e.g:

```clojure
(rss/channel-xml {:title "Foo" :link "http://foo/bar" :description "some channel"}
                 {:title "test"
                  :category [[{:domain "http://www.microsoft.com"} "MSFT"]
                             [{:domain "http://www.apple.com"} "AAPL"]]})
```

**Comment by lacarmen** [comment]
@sanel And just pushed out cryogen-core 0.1.25 with the new clj-rss :)

**Comment by sanel** [comment]
@yogthos @lacarmen thanks for fast updates :)

**Comment by sanel** [comment]
Hi @lacarmen,

Have you managed to add this? Haven't had time lately to work on this...

**Comment by lacarmen** [comment]
Yes, it was fixed in `clj-rss` and the dependency has been updated in cryogen :)
