### ISSUE TITLE
home.html pointing to a specific page

### ISSUE THREAD

**Issue by tuhlmann** [cryogen-project/cryogen#72]
I'm getting started with cryogen, please excuse if this is a stupid question or the wrong channel to ask...

I'm trying to make the home.html page point to a specific markdown page in the /pages directory.
In the example config it shows the latest blog post, how would I make it render the contents of, say, the about.md page?

Thanks!

**Comment by lacarmen** [comment]
There isn't an easy way to do this right now so maybe we can flag this as a future enhancement.

The only thing I can suggest right now is to hard code the content into your home.html file.

**Comment by tuhlmann** [comment]
Thanks for the feedback, Carmen. That's exactly what I did, code the home page as html.
I think it might be a nice enhancement, for me it's not pressing in any way.
