### ISSUE TITLE
Post metadata

### ISSUE THREAD

**Issue by niamu** [cryogen-project/cryogen#73]
Very new Clojure programmer and have been actively looking at the source code of Cryogen and planning on making some pull requests in the future. I was thinking I'd start with this feature as something I have started on my own and see what your thoughts were.

I'm looking for a feature that will allow `:slug` in the post metadata which will override the default slug for the post. In time, this could also expand to adding `:date` which would free up the filename restrictions of posts. This would be particularly useful for people migrating from another CMS or static site generator to Cryogen.

Is this something planned for Cryogen or something you'd be willing to accept as a possible pull request in the future?

**Comment by lacarmen** [comment]
I would be open to adding `:date` to the post metadata but can you clarify what the use case for the `:slug` would be?

**Comment by niamu** [comment]
`:slug` may ultimately be misplaced and should exist in the main config file. I haven't thought it through completely yet, to be honest.

The use case involves the situation where you want to alter the URL structure of your site. Currently (unless I'm mistaken) you can't have a post URL be something like `example.com/posts/fizzbuzz` or `example.com/posts/1` where the post slug is just the title or an ID number or something else outside of the current fixed structure of `YYYY-MM-DD-title.html`.

I can imagine a solution to this involving some sort URL structure key in the main `config.edn` file.

**Comment by lacarmen** [comment]
>Currently (unless I'm mistaken) you can't have a post URL be something like example.com/posts/fizzbuzz or example.com/posts/1 where the post slug is just the title or an ID number or something else outside of the current fixed structure of YYYY-MM-DD-title.html.

Well if you want you use a structure outside of `yyyy-MM-dd-title.md` for the Markdown files then the `:date` parameter would take care of that.

Your use case is a little confusing to me. It sounds like you want to use the slug as a post's uri when it ultimately gets rendered into an html file so why should it exist in the main config file? This implies that the slug parameter should be post-specific, not global. If this is the use case that you're going for then it doesn't really seem like a feature worth adding because how often is a user going to name their Markdown file `foo.md` but want it to render as `bar.html`?

**Comment by niamu** [comment]
I think that's a much clearer line of reasoning than I had. My only remaining use case that could be solved with some clever URL rewriting on the server is the case where you have a post called `foo.md` and it renders as `foo.html` but you actually want it rendered as `foo/index.html`. I know that this is something that Jekyll and other static site generators offer as an option, but it may not fit into the design goals of Cryogen.

Unless there are objections, I think I'll work on adding `:date` to the post metadata as a pull request over the next couple of days.

**Comment by lacarmen** [comment]
It's still a very niche use case so I'd say go ahead with the `:date` parameter but let's leave out the `:slug`.
