### ISSUE TITLE
How to make a static site with posts on a tab

### ISSUE THREAD

**Issue by frap** [cryogen-project/cryogen#76]
Simple question but how do you use cryogen to make a static pages site? I.e posts/ blogs are not on main page? I want to use home as index not the the blogs.

**Comment by lacarmen** [comment]
You can replace lines [4-18 in home.html](https://github.com/cryogen-project/cryogen/blob/master/src/leiningen/new/cryogen/themes/blue/html/home.html) with whatever content you'd like to show up in the index.

**Comment by frap** [comment]
Thanks just worked it out by reading your code :).  Maybe a suggestion on docs for beginners like me is the hierachy of Selmer templates and how they are related? If you want I can do a graphviz flow diagram of it? Then its clear that everything is based off the home.html template.

**Comment by lacarmen** [comment]
Yes, I think that would be nice :) I need to do a lot of documentation updates since quite a bit has changed lately and I would gladly include a diagram.

**Comment by frap** [comment]
Carmen

I think i did a pull/request and updated the docs and a diagram. Not sure
if I did it right? can you check whether your received the pull request?

Cheers Andrew

---
Gas gas@red-elvis.net
24A beauchamp St
Karori 6010
Nouvelle Zelande
+64 4 9798840

2015-08-05 1:58 GMT+12:00 Carmen La <notifications@github.com>:

**Comment by lacarmen** [comment]
Hi Andrew, 

I did receive the pull request, I've just been busy with work and wanted to take the time to review the changes first. I've merged it in now and the changes are on the documentation site.

**Comment by frap** [comment]
Hi Carmen,

I understand the work thing :) . Sorry for pestering just wasn't sure I had
done it right

Cheers Andrew

---
Gas gas@red-elvis.net
24A beauchamp St
Karori 6010
Nouvelle Zelande
+64 4 9798840

2015-09-01 15:23 GMT+12:00 Carmen La <notifications@github.com>:
