### ISSUE TITLE
Compile cryogen site command

### ISSUE THREAD

**Issue by oubiwann** [cryogen-project/cryogen#79]
I'd like to be able to compile cryogen sites as part of a custom build chain, without having to manually run a ring server and then stop it. Is there a command to do this yet?

If not, I can take a look at creating a ``lein`` plugin that would be available to cryogen sites so that maybe something like the following would work:

```bash
$ lein compile cryogen
```

Is something like this already available? (I could very well be over-looking something ...)

**Comment by lacarmen** [comment]
`lein run` should do the trick :)

**Comment by oubiwann** [comment]
Ah, thanks! That's what I was looking for :-)
