### ISSUE TITLE
[Feature Request] Podcast Support

### ISSUE THREAD

**Issue by ClashTheBunny** [cryogen-project/cryogen#80]
I think it would be fairly easy to add, as long as the files are in the right place on the server.

It would require a second RSS feed generated for the pod-cast only content, and the main feed would be both the pod-cast items and the regular blog posts.

It would also need the extra meta-data added to the body of the pod-cast posts.

The last thing it could benefit from is an automatic "MP3 to post" based on ID3 tags, but this would be icing.

Would this be something you would be interested in integrating in if I came up with a pull request?  Does the architecture of the change seem like it would fit with cryogen?

I'm looking for a way to put all of my audio-books on my iPhone, and there seems to be no good way besides pod-casts.

**Comment by lacarmen** [comment]
I'm a little confused with how the podcast posts would look/how they would be different from regular posts. I imagined they would be like a regular post with a link to the mp3 for the listener to download (which can be done without modifying the compiler I think) but let me know if you were thinking of something different.

The second RSS feed could be generated by simply adding a `podcast` tag to the podcast post and then specifying it under the `rss-filters` key in `config.edn`.

The last thing I'd like to know is what extra meta-data do you believe would have to be added and what would it be used for?

**Comment by ClashTheBunny** [comment]
There are many different extra tags that work well when pod-casting that aren't in the clj-rss "accepted tags" list:
http://www.apple.com/itunes/podcasts/specs.html#rss
so it looks like this is more of a clj-rss enhancement request?

Other than that it does seem like it's very easy to manually set up a pod-cast with cryogen already.  Maybe the enhancement would be having another directory other than posts and pages that contains media items that are automatically fed into the pod-cast feed with all of the above extra meta-data read from the media file.  That way I can just add a video or audio file to the directory and an appropriate post is generated based on the contents.

Thanks for taking a look at this!

**Comment by ClashTheBunny** [comment]
For example, to get an image to show up for your pod-cast, you need the feed to have an `<image>` tag for the `channel`.  This is currently tough to to with the way that the feed is generated here:
https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/rss.clj#L19

It needs to have a way of adding optional meta-data to a tag.  This could be stored in the global config.edn (as a map, instead of as simple tags), or it could be stored in a separate but optional `<tag>-metadata.edn` or even the header for any post within that tag could add things to the channel meta-data map.
