### ISSUE TITLE
Ring server fails to start when img folder does not exists 

### ISSUE THREAD

**Issue by sbondaryev** [cryogen-project/cryogen#82]
Step to reproduce:
1. create a new project
2. create a git repo and add the project (the empty img folder is not added by git)
3. clone the project in a new directory 
4. try to start the ring server
error:  Error: resource resources/templates/img not found

possible solution: ignore resource if there is no corresponding folder?

**Comment by lacarmen** [comment]
That error is the intended behaviour. It would be worse if the compiler just silently ignored a non-existent resource. 

As for the git behaviour, I suppose we can remove "img" from the resources vector but I had it there in the first place as an example.

**Comment by sbondaryev** [comment]
In this case it could by useful to have a picture (the cryogen logo for example) in the "img" with code example of using it?
This also resolves the git issue.

**Comment by yogthos** [comment]
seems like a good solution to me ;)

**Comment by lacarmen** [comment]
Fixed in #94 and deployed to Clojars as version `0.2.26`.
