### ISSUE TITLE
expand markdown link support to include named links

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen#84]
add support for markdown links that look like this:

```
[GeekDesk v3][]
```

and are later referenced by name like this:

```
[GeekDesk v3]: http://www.geekdesk.com/geekdesk-v3
```

**Comment by lacarmen** [comment]
This would be a change in [markdown-clj](https://github.com/yogthos/markdown-clj), not Cryogen.

**Comment by chadhs** [comment]
Thanks for the heads up, i'll close this.  @lacarmen I also noticed that it does work if you include the name like `[this is a link][named link]`.  When the link text and named like match you can exclude the name.  I'll report this to markdown-clj.

**Comment by chadhs** [comment]
https://github.com/yogthos/markdown-clj/issues/69
