### ISSUE TITLE
add support for date definition inside post file

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen#85]
it would be cool to be able to define posts dates inside the post so files and thus post urls don't have to include the date.

the address for this post could then be http://example.com/posts/build-a-20-dollar-standing-desk-in-20-minutes.html

```
{:title "Build a $20 Standing Desk in 20 Minutes"
:layout :post
:date "2015-05-12"
:tags ["productivity" "ergonomics" "standing-desks" "DIY"]}
```

**Comment by lacarmen** [comment]
This was added in cryogen-project/cryogen-core#33. Sorry I don't have documentation on this right now; I have a lot to update.

Please note that the date format must match the format specified in your `config.edn`

**Comment by chadhs** [comment]
@lacarmen i created a branch and updated the docs for you.  super noobie question… to do a pull request do i need to fork the repo and make my change in a branch in my fork?

**Comment by lacarmen** [comment]
I think you can just do the change under master in your fork then open a pull request here :)

**Comment by chadhs** [comment]
thanks, i just figured that out and did so.  if you don't like the wording etc let me know and i'll change it.  :-)

**Comment by chadhs** [comment]
https://github.com/cryogen-project/cryogen/commit/78497f002123448767714e79c6c6c5c44fba21e1
