### ISSUE TITLE
bug? when `previews?` is set to true the /p/<number> pages don't work when published to github

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen#92]
bug? when `previews?` is set to true the /p/<number> pages don't work when published to github

for now i set previews to false and just have one post featured on my homepage.

**Comment by chadhs** [comment]
^ i don't mind setting previews back to true so you can see that it just downloads a "2" file when you try to go to the next page.

**Comment by lacarmen** [comment]
Oh I see why, the pages are being spit out as just `p/2` rather than `p/2.html` so when you try to access them it just downloads the file. I'll have a fix up in a moment.

**Comment by chadhs** [comment]
Awesome thank you!  Really goofy question for you @lacarmen , how do I update my site / lein project to take advantage of your fix?

**Comment by lacarmen** [comment]
Update the `cryogen-core` dependency in your `project.clj` :)

**Comment by chadhs** [comment]
Cool, that was a guess but wanted to be sure, thank you! 😎

**Comment by lacarmen** [comment]
@chadhs Feel free to close this if it works for you :)

**Comment by chadhs** [comment]
working beautifully thank you.
